### ISSUE TITLE
Undefined `registerMediaCollections` method is called on related resources

### ISSUE THREAD

**Issue by acstll** [dmitrybubyakin/nova-medialibrary-field#10]
Hi there!

I got this issue, I'm not sure the problem is in this package, or in `spatie/laravel-medialibrary` (or even Nova itself)… I'm trying here first.

I'm getting a `Call to undefined method App\{Model}::registerMediaCollections()` error when I try to create or edit a resource that is related to another one that uses Medialibrary. Let me explain:

- There's model `Foo`, which uses Medialibrary (uses `HasMediaTrait`).
- There's model `Bar`, with no images, no Medialibrary.
- `Foo` has a `hasMany` relationship to `Bar`

```php
  // in App\Nova\Foo 

  // ..fields..
  HasMany::make('Bar'),
```

I'm guessing something is trying to call `registerMediaCollections` on Foo *and* any other related models, namely `App\Bar::registerMediaCollections()`…

To fix it temporarily I added the `HasMediaTrait` to my `Bar` model, although I don't need it.

Any ideas?

(Thank you for this package 👍)

**Comment by dmitrybubyakin** [comment]
@acstll Fixed. Thank you for pointing this out.

**Comment by vrtxims** [comment]
@dmitrybubyakin Thank you!
