### ISSUE TITLE
single() not working correctly with attachExisting()

### ISSUE THREAD

**Issue by JonathanDoelan** [dmitrybubyakin/nova-medialibrary-field#100]
Instead of replacing the selected existing Media, it is added to the list.

```
Medialibrary::make(…)
	->attachExisting()
	->single()
```

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan Is your collection is the single file collection? https://spatie.be/docs/laravel-medialibrary/v9/working-with-media-collections/defining-media-collections#single-file-collections

**Comment by JonathanDoelan** [comment]
Yes … like this:

```
    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('teaser')->singleFile();
    	$this->addMediaCollection('gallery');
    }
```

Ah! I figured out that the problem only occurs on the CREATE form. So maybe it has to do something with the TransientModel?

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan Yes, that's because of the TransientModel. I'll fix that.

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan Could you please check it out? The master branch.

**Comment by JonathanDoelan** [comment]
Yes, it works. Nice, thx!
