### ISSUE TITLE
help() not appearing on Medialibrary field or custom fields

### ISSUE THREAD

**Issue by JonathanDoelan** [dmitrybubyakin/nova-medialibrary-field#101]
Help text does not appear on Medialibrary field. Also help text within the `-fields()` method is not appearing.

```
Medialibrary::make(…)
	->help( 'NOT APPEARING' )
	->fields(function(){
		Text::make(…)
			->help( 'NOT APPEARING' )
	})
```
:(

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan Can't reproduce. What version of Nova do you use? 
![image](https://user-images.githubusercontent.com/11477505/100542410-58981100-3252-11eb-8600-83aeb78ae790.png)

**Comment by JonathanDoelan** [comment]
nova version is `"version": "3.15.0"` and it only happens with your package …
:(

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan Ok. I'll try to find out and fix that.

**Comment by JonathanDoelan** [comment]
[https://github.com/laravel/nova-issues/issues/3095#issuecomment-737142016](https://github.com/laravel/nova-issues/issues/3095#issuecomment-737142016)

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan Thank you. Fixed.
