### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by steven-backerclub** [dmitrybubyakin/nova-medialibrary-field#107]
Would be great if we could watch the [Nova PHP 8 Support ticket](https://github.com/laravel/nova-issues/issues/3087) and when ready, include the new version here as well (something like `"php": "^7.4|^8.0"`) -- assuming the new version is acceptable in this package.

**Comment by steven-fox** [comment]
Hi @dmitrybubyakin. Nova officially has support for PHP8 as of January 5th. Do you think it's safe to push a new release tag? I see you already have php 8 in the composer file on the master branch.

**Comment by dmitrybubyakin** [comment]
@steven-fox Forgot to release it. Thanks for reminding me.

**Comment by steven-backerclub** [comment]
You're welcome!
