### ISSUE TITLE
Croppable-feature deletes tmp folder on production server!

### ISSUE THREAD

**Issue by JonathanDoelan** [dmitrybubyakin/nova-medialibrary-field#110]
Everything works fine on my local machine, but when deploying to our production server, applying the croppable-feature as well as "regenerating" through your UI causes some serious issue:

The temp-directory (sys_temp_dir, upload_tmp_dir) well be deleted. How can that be possible? Not sure if it is a problem with `Spatie\Image\GlideConversion::save()` or with your implementation. The thing is, that uploading an image works perfectly, but as soon as I’m (visually) cropping the image with your tool, it deletes the tmp-folder. That‘s why I tend to believe that you’ve probably done a wrong implementation.

Because no file upload works without a temporary directory, i have to recreate this folder manually everytime it is deleted. This is quite annoying!

I made a test and removed the line with `rmdir($conversionResultDirectory);` in `Spatie\Image\GlideConversion::save()` like this (hot fix!):

```
if ($this->directoryIsEmpty($conversionResultDirectory) && $conversionResultDirectory !== '/tmp') {
    //rmdir($conversionResultDirectory);
}
```

… and indeed, it solved my problem. But I don’t know why we need this line there, so maybe I forget something when I comment out this line.

So … this means that if the `$conversionResultDirectory` is empty and is NOT `/tmp` then it will be deleted … 
… so when cropping with your tool `$this->directoryIsEmpty($conversionResultDirectory)` returns `true`, and `$conversionResultDirectory !== '/tmp'` will always be true (my temp-folder for example is `/var/tmp` or `/home/sites/xxx/site/tmp`) … and then the tmp-directory will be deleted.

Fyi: when initially uploading the image `$this->directoryIsEmpty($conversionResultDirectory)` returns `false` … which makes sense … 

so why do we run through `Spatie\Image\GlideConversion::save()`, when we don’t upload a new image … and in which case does deleting this folder make sense? (I’ve opened an issue on this here too: https://github.com/spatie/image/issues/117)

Would be nice if you could have a look at this.

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan Hi. I think this issue is related to https://github.com/spatie/laravel-medialibrary

**Comment by JonathanDoelan** [comment]
Solved with [https://github.com/spatie/image/pull/118](https://github.com/spatie/image/pull/118)
