### ISSUE TITLE
How to change the order of existing images/files?

### ISSUE THREAD

**Issue by JonathanDoelan** [dmitrybubyakin/nova-medialibrary-field#115]
If I click on the button that selects existing media, I want the list ordered by the last updated.

How to change the order?

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/src/Fields/Medialibrary.php#L102

**Comment by JonathanDoelan** [comment]
@dmitrybubyakin Thx! Did not see that ;)
