### ISSUE TITLE
When I create a new medialibrary with the single attribute, it  can hold multiple files

### ISSUE THREAD

**Issue by moustafaart4muslim** [dmitrybubyakin/nova-medialibrary-field#117]
I have created a single field as follows:
```
Medialibrary::make('test', 'test'  , 'test' )
->accept('image/*')
->autouploading()
->hideFromIndex()
->single()
->croppable('conversionName', [
    'rotatable' => false,
    'zoomable' => false,
    'cropBoxResizable' => false,
])         

```

Then I choose file to upload, then click replace file and choose a new  one, it doesn't replace the old file, but it's added to it as if it's a multiple images field.

**Comment by dmitrybubyakin** [comment]
@moustafaart4muslim https://spatie.be/docs/laravel-medialibrary/v9/working-with-media-collections/defining-media-collections#single-file-collections
