### ISSUE TITLE
Indicate boolean values by framing the photo

### ISSUE THREAD

**Issue by rapitkan** [dmitrybubyakin/nova-medialibrary-field#12]
It would be really nice if a photo could be framed with certain color depending on the boolean values of the photo.

**Example:**

There's an 'alert' property in custom_properties and a user needs to know which photos have alert: true. At the moment the only way to find it out is to open the pop-up of every photo one by one. It's a time consuming task and the user might not remember the photos that have alert state after he/she has opened and closed all the pop-ups.

The photo below illustrates how the boolean values could be presented in UI. Every photo with alert state could be framed with - for example - red border. So the user would immediately see the situation related to the 'alert' boolean value.

If there were more boolean values (alert is just an example) those could be shown by framing the photo with a different color. So there could be multiple thin borders around the photo. There could be an explanation section on top of the gallery: red border = 'Alert! Do something quickly', yellow border = 'Might be a problem soon' etc.

![media](https://user-images.githubusercontent.com/2033731/51840990-35c70980-2316-11e9-95b4-5d5c94c44b14.jpg)

**Comment by dmitrybubyakin** [comment]
I'll do something like this.

![](https://cdn.discordapp.com/attachments/535468360956248069/539455970234073128/unknown.png)

**Comment by tmartty** [comment]
@dmitrybubyakin @rapitkan was this actually implemented?

**Comment by dmitrybubyakin** [comment]
@tmartty It was removed.
