### ISSUE TITLE
Renaming files does not work

### ISSUE THREAD

**Issue by etenzy** [dmitrybubyakin/nova-medialibrary-field#13]
When the file_name attribute gets edited in nova the file itself doesn't get renamed. This causes errors, because medialibrary can't find a file with the expected name.

**Comment by dmitrybubyakin** [comment]
@etenzy Hi. What version of `spatie/laravel-medialibrary` are you using?

**Comment by dmitrybubyakin** [comment]
@etenzy Could you provide more information?

**Comment by etenzy** [comment]
laravel/framework: v5.7.21
spatie/laravel-medialibrary: 7.5.5
dmitrybubyakin/nova-medialibrary-field: 1.1.4

Causing at the "Edit Media" Dialog

**Comment by dmitrybubyakin** [comment]
This library just changes the `file_name` attribute. File should be renamed automatically. https://github.com/spatie/laravel-medialibrary/blob/master/src/MediaObserver.php#L20

**Comment by etenzy** [comment]
I've extended the original model.

When i choose files and hit upload the observers works properly.
POST nova-vendor/dmitrybubyakin/nova-medialibrary-field/store

In the Edit Media dialog the observers are not executed.
PUT nova-api/{resource}/{resourceId}

**Comment by etenzy** [comment]
That worked, Thank you!

the requirement of an custom media resource when using a custom, or extended model should be in the docs (just a suggestion)
