### ISSUE TITLE
Using a thumbnail instead of original image

### ISSUE THREAD

**Issue by bilogic** [dmitrybubyakin/nova-medialibrary-field#141]
Hi,

Is there a way to specify using a thumbnail in `index`, i find that it currently loads the original image. Thank you.

**Comment by dmitrybubyakin** [comment]
@bilogic https://github.com/dmitrybubyakin/nova-medialibrary-field#previewusing

**Comment by bilogic** [comment]
Beautiful! Thanks! Is there a built-in way to show the original image in a lightbox when clicked?

**Comment by dmitrybubyakin** [comment]
@bilogic You need to override the index field.

**Comment by bilogic** [comment]
Ok, got it. Thank you.
