### ISSUE TITLE
MediaLibrary v10 support

### ISSUE THREAD

**Issue by seobrain** [dmitrybubyakin/nova-medialibrary-field#150]
Hi,

Migration to Laravel 9 requires MediaLibrary 10 package, which in its turn is not yet supported by your awesome package.

Could you please bump dependencies support for ML10?

Thanks in advance!

**Comment by dmitrybubyakin** [comment]
@seobrain Hi! Could you please check out a new version?

**Comment by seobrain** [comment]
Hey,

Works like a charm now, thanks a bunch for your prominent support!
