### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by illambo** [dmitrybubyakin/nova-medialibrary-field#157]
Any plan about support for laravel nova 4? Thanks

**Comment by dmitrybubyakin** [comment]
@illambo Hi, don't really have time to support this package

**Comment by illambo** [comment]
Ok thanks

**Comment by ChristianPavilonis** [comment]
I see [this fork](https://github.com/aemaddin/nova-medialibrary-field) with a few commits for Nova 4.
You may want to try that out.

**Comment by theimerj** [comment]
Hello, I will open a PR in the following days. I am getting quite close [here](https://github.com/theimerj/nova-medialibrary-field). Apart from other stuff I still have to make generated conversions work, fix tests and so on. But if someone wants to try it with Nova 4 installation, the crucial parts are working ok now.

**Comment by sp4r74cus** [comment]
hi @theimerj 
Thank you for the efforts to make this compatible with Nova 4! 

I couldn't find where to open an issue in your fork. so i'll add it here.

the id of the field is not generated correctly, it's `id="inputundefined"` and when having multiple fields in the same resource only the first one works.
<img width="1740" alt="Screen Shot 2022-05-01 at 12 54 48" src="https://user-images.githubusercontent.com/864292/166141114-e6b133c0-b8fa-4239-b2c8-a54f6a9cdd13.png">

**Comment by theimerj** [comment]
Hello @sp4r74cus, I opened the issue tab in the [fork](https://github.com/theimerj/nova-medialibrary-field), so we can move the conversation there.

**Comment by theimerj** [comment]
Hello everyone, the PR #160 just landed. Please help out with testing and adjustments, if you can. It is not 100% done, it still needs quite some polishing.

@dmitrybubyakin could you please remove the #159 i accidentally created from wrong branch? Thank you.

**Comment by tmartty** [comment]
any news on this?

**Comment by theimerj** [comment]
> any news on this?

Actually yes, [@kreejzak](https://github.com/kreejzak) is looking into it and we will merge soon.
