### ISSUE TITLE
Problem with UUID primary keys for models

### ISSUE THREAD

**Issue by jacob418** [dmitrybubyakin/nova-medialibrary-field#161]
In my project I'm using UUID for the primary keys of models, therefore I had to change the `media` table to use `uuidMorphs` instead of normal `morphs`. `\DmitryBubyakin\NovaMedialibraryField\Http\Requests\MedialibraryRequest::resourceExists` checks weather a model exists by testing weather the param `resourceId` is numeric. Since UUID's are not numeric `\DmitryBubyakin\NovaMedialibraryField\TransientModel` comes into use. However this model has a numeric key, so it will cause an exception `[...]  invalid input syntax for type uuid: "1" (SQL: select * from "media" where "media"."model_id" = 1 and "media"."model_id" is not null and "media"."model_type" = DmitryBubyakin\NovaMedialibraryField\TransientModel)`.

Is there any way to get this package to work with UUID's?

**Comment by dmitrybubyakin** [comment]
@jacob418 UUID as PK is not supported

**Comment by zsoltgyure** [comment]
Hi.

You can easily solve this issue by replacing the `MedialibraryRequest` class in the container.

Create a request class
```
php artisan make:request MediaLibraryRequest
```

Extend the original class and overwrite the `resourceExists` method
```
<?php

namespace App\Http\Requests;

class MediaLibraryRequest extends \DmitryBubyakin\NovaMedialibraryField\Http\Requests\MedialibraryRequest
{
    public function resourceExists(): bool
    {
        return $this->route('resourceId') !== 'undefined';
    }
}

```

Replace the class in the container in your `AppServiceProvider`
```
class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(MedialibraryRequest::class, \App\Http\Requests\MediaLibraryRequest::class);
    }
}
```

**Comment by jacob418** [comment]
@zsoltgyure ty for the tip, I hope i get to try it out some day.
