### ISSUE TITLE
Doesn't work with STI(Single Table Inheritance) parent model

### ISSUE THREAD

**Issue by webappbuilder** [dmitrybubyakin/nova-medialibrary-field#17]
I use https://github.com/tightenco/parental package for STI models. For ex., i have App\Models\Content\Header model which extends App\Models\Content\Content basic one. I try attach file to Header Resource (with Header model defined). While processing upload i get message: Call to undefined method App\Models\Content\Content::registerAllMediaConversions(). But i deal with Header model, not STI parent one(e.g. Content).

**Comment by dmitrybubyakin** [comment]
@webappbuilder Hi. Are you using the `spatie/laravel-medialibrary`? Could you show your model code?
