### ISSUE TITLE
Media form field when creating a resource

### ISSUE THREAD

**Issue by mauricehofman** [dmitrybubyakin/nova-medialibrary-field#18]
>  If there is any reason to show it on forms, let me know.

It would be nice to have a media field in the form when creating a new resource. Its a bit counter intuitive to first create the resource, and then afterwards editing the resource to add the media files. Or am i missing something here?

**Comment by dmitrybubyakin** [comment]
Hi @mauricehofman. Look #3

**Comment by mauricehofman** [comment]
If #3 is done correctly as you mentioned, i have a field when creating a new resource?

Because when i add the field `HasMany::make('photos'),` or `HasMany::make('media'),` its says 'Class not Found'. Which is true, because Medialibrary does not have a class (nova resource), and 'photos' is the Medialibraries 'model_type'

**Comment by dmitrybubyakin** [comment]
@mauricehofman When you are using the `HasMany` field, you should make sure that the `Media` resource is defined. 
https://nova.laravel.com/docs/1.0/resources/#registering-resources

**Comment by mauricehofman** [comment]
I`m trying to understand, but Spatie's media library does not have a model, right? So when registering the `Media` resource in nova, which model does it references?

**Comment by dmitrybubyakin** [comment]
@mauricehofman Look https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/src/Resources/Media.php

**Comment by slackjaw47** [comment]
When I tried this Nova keeps reading it as App/Nova/Medium and its clearly App/Nova/Media.  And its registered in the NovaServiceProvider as Media as well.  What is going on?  Is Nova trying to use autocorrect?

**Comment by slackjaw47** [comment]
Actually I had to use the string 'Medias' so that Nova would infer the correct singular resource name. But it still says that App/Nova/Media doesn't exist. Thoughts?

**Comment by jphms** [comment]
@slackjaw47 try creating a resource named `Media` with fields like they are in here, for instance:
https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/src/Resources/Media.php . Worked for me, but it is not showing on forms though 👎 just on the details view.
