### ISSUE TITLE
"Update Media" button is disabled after Laravel Nova v4.28.0

### ISSUE THREAD

**Issue by tmartty** [dmitrybubyakin/nova-medialibrary-field#186]
Starting from Laravel Nova v4.28.0, when editing a media item fields, the modals "Update Media" button can't be clicked and shows as disabled:
![image](https://github.com/dmitrybubyakin/nova-medialibrary-field/assets/24498673/578f0dab-9f57-4bea-a9fe-efdb576fb18c)

![image](https://github.com/dmitrybubyakin/nova-medialibrary-field/assets/24498673/19e656c5-a7d3-4f9f-8032-f7766547886b)

If I downgrade Laravel Nova to v4.27.14 (the latest previous version), it works fine.
The release notes for v4.28.0 are:
- Nova will now display page titles with the page title first and the application name second.
- Fixed an issue where Number filters weren't correctly applied when the value was zero.
- Fixed an issue where MorphTo relationship labels were ignoring field labels on detail views.
- Fixed an issue where Repeater fields using unique fields weren't correctly saving.

Btw, I'm using dmitrybubyakin/nova-medialibrary-field v4.0.5

**Comment by everzel** [comment]
Hi! This issue has been resolved in [v4.0.6](https://github.com/dmitrybubyakin/nova-medialibrary-field/releases/tag/4.0.6).
