### ISSUE TITLE
this package is reay on 'spatie/laravel-medialibrary' ?

### ISSUE THREAD

**Issue by yuqinghong** [dmitrybubyakin/nova-medialibrary-field#23]

**Comment by yuqinghong** [comment]
I follow the doc to edit code on my program, bug id always report errors of "undefined method App\{my model}:: registerMediaCollecitons() "

**Comment by dmitrybubyakin** [comment]
@yuqinghong Have you resolved this problem?

**Comment by yuqinghong** [comment]
> @yuqinghong Have you resolved this problem?
@dmitrybubyakin Yes, I've solved it. It base on the package of `spatie/laravel-medialibrary'` when i To configure the `medialibrary ` , this package will run!
