### ISSUE TITLE
Class 'App\Nova\MediaLibrary' not found

### ISSUE THREAD

**Issue by CyrilBlankaert** [dmitrybubyakin/nova-medialibrary-field#24]
Hi, 

I have a problem when I want to use MediaLibrary:: in my Ressource ! 

`Class 'App\Nova\MediaLibrary' not found`

How to declare it ? 
Thank you :)

**Comment by dmitrybubyakin** [comment]
@CyrilBlankaert Hi. Did you import it?

```php
use DmitryBubyakin\NovaMedialibraryField\Fields\MediaLibrary
```

**Comment by CyrilBlankaert** [comment]
No, now it works !
Thank you :)

**Comment by akizor** [comment]
> @CyrilBlankaert Hi. Did you import it?
> 
> ```
> use DmitryBubyakin\NovaMedialibraryField\Fields\MediaLibrary
> ```

Hello, it's `Medialibrary` not `MediaLibrary`. It throws class not found when strict PHP settings.
