### ISSUE TITLE
How can we define the path of a gallery ?

### ISSUE THREAD

**Issue by CyrilBlankaert** [dmitrybubyakin/nova-medialibrary-field#25]
I want to have a folder with my ressource name where all the images are on (and not a folder where the name of the folder is the id) How can it be possible ? 

Like : 

> storage/public/$post_name/$img_filename.extension

Thanks for the help (again :p )

**Comment by dmitrybubyakin** [comment]
@CyrilBlankaert https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure

**Comment by CyrilBlankaert** [comment]
Thanks, it helped me ! :) 
But I have a problem now : When I want to delete an image via Laravel Nova, the image is not deleted ! 
I don't understand why ?

Here is my CustomPath code : 

```
<?php

namespace App;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

use Illuminate\Support\Facades\DB;

class CustomPathGenerator implements PathGenerator
{
  
    public function getPath(Media $media): string
    {

        if($media->model_type === 'App\Posts')
        {

          $town = DB::table('posts')->where('posts.id', $media->model_id)->first();
          return 'posts_gallery/' . $post->post_slug . '/' . md5($media->name);

        }
    }

    public function getPathForConversions(Media $media) : string
    {
        return $this->getPath($media).'conversions/';
    }

    public function getPathForResponsiveImages(Media $media): string
    {
        return $this->getPath($media).'responsives/';
    }
}
```

**Comment by CyrilBlankaert** [comment]
Solved ! 
Juste add '/' at the end of the return.

`return 'posts_gallery/' . $post->post_slug . '/' . md5($media->name) . '/';
`
