### ISSUE TITLE
Save under hashied filename

### ISSUE THREAD

**Issue by h-zone** [dmitrybubyakin/nova-medialibrary-field#26]
Hi!
In case of localized filenames (greek, cyrillic, chineese, etc), will be good to be rename files while saving into the storage.

Or i can not see how to flag uploader/adder to rename file.

**Comment by dmitrybubyakin** [comment]
@h-zone Hi. have a look at his https://github.com/dmitrybubyakin/nova-medialibrary-field#store-and-replace-callbacks

**Comment by h-zone** [comment]
Still dont understand how to rename filename into hashied name

**Comment by dmitrybubyakin** [comment]
@h-zone You can do something like this:
```php
Medialibrary::make('Images', 'post_images')
    ->storeUsing(function (FileAdder $fileAdder, UploadedFile $file) {
        return $fileAdder->usingFileName(<...>);
    })
```

**Comment by h-zone** [comment]
->usingFileName() losts extension, but i see, thnx!
