### ISSUE TITLE
Use getTemporaryUrl() for pirvate files on s3 disk

### ISSUE THREAD

**Issue by tobz-nz** [dmitrybubyakin/nova-medialibrary-field#27]
The download/view links fail if files are stored on S3 and are private. Using `getTemporaryUrl()` in this case will sort out this problem.

I'm Happy to PR a fix for this.

**Comment by dmitrybubyakin** [comment]
Hi @tobz-nz. You're free to use your own MediaResource. https://github.com/dmitrybubyakin/nova-medialibrary-field#custom-media-resource

**Comment by tobz-nz** [comment]
I am - it doesn't fix incorrect download url though, which is set in `Medialibrary->serializeMedia()` 

https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/984b45d9d1829314d87e372c1aaf2c956db2d365/src/Fields/Medialibrary.php#L303


Unless I've missed a way to set it via the resource?

**Comment by dmitrybubyakin** [comment]
@tobz-nz Thank you. Just fixed that. Check it out. https://github.com/dmitrybubyakin/nova-medialibrary-field#custom-download-url

**Comment by tobz-nz** [comment]
Perfect 👍
