### ISSUE TITLE
Бага связанная с локализованностью

### ISSUE THREAD

**Issue by h-zone** [dmitrybubyakin/nova-medialibrary-field#28]
Хотя может виновата моя невнимательность.
`resources/js/components/Medialibrary/Modal/DetailModal.vue`
```
<h4 class="text-90 font-normal text-2xl flex-no-shrink">{{ resource.id.panel }}</h4>
```
в итоге получаем скриншот
![2019-07-15_14-23-18](https://user-images.githubusercontent.com/1150044/61212889-242ebe00-a70c-11e9-9733-79a4693808a7.png)

**Comment by h-zone** [comment]
а так хотелось получить `Подробности`

**Comment by h-zone** [comment]
короче говоря, моё виденье сунуть туда `__( 'Detail' )`

**Comment by dmitrybubyakin** [comment]
@h-zone В Nova эта проблема решена с остальными диалогами?

**Comment by h-zone** [comment]
не уверен даже.
девид и тейлор тупо и постоянно пишут отмазки на решение очевидных проблем.

**Comment by h-zone** [comment]
@dmitrybubyakin как временное (а в следствии постоянное) решение, имхо, стоит тупо забить туда __(Detail) и забыть как страшный сон до лучших времён.

Также я считаю, что они занимаются версией 3, где 90% текущих проблем будет решено.

**Comment by h-zone** [comment]
ещё бага. возможно из за обновления новы.

НЕ РАБОТАЕТ:
```
Text::make('Size')->displayUsing(function () {
    return $this->resource->humanReadableSize;
})->exceptOnForms(),
```
РАБОТАЕТ:
```
            Text::make( __('Size'), function()
            {
                return $this->resource->humanReadableSize;
            })->exceptOnForms(),
```
Нова 2.0.9, Лара *.28

**Comment by h-zone** [comment]
Чёрт - день дерьмо.
Отвалился редактор кастомных пропертей.
Полей редактирования больше нет.

**Comment by h-zone** [comment]
знаю, спамлю уже. цейтно у меня :(
при попытке редактировать из несущего медиа объекта, отсутствует кусок параметров:
`?editing=true&editMode=update&viaResource=&viaResourceId=&viaRelationship=`
