### ISSUE TITLE
Кропилка, добить функционал + бага

### ISSUE THREAD

**Issue by h-zone** [dmitrybubyakin/nova-medialibrary-field#29]
Очень хотелось бы видеть доп функционал кропилки в виде ограничения пропорциями сторон изображения.
Например в свойствах принимать либо коэфф типа `1.33(3)` или `16:10`

Также хотелось бы, чтобы кропилка по умолчанию выбирала всё изображение целиком.
Так как приходится постоянно дотягивать края, и ели (**бага**) зажатая мышь уходит за пределы попапа с кропом то попап сворачивается.

**Comment by h-zone** [comment]
@dmitrybubyakin в планах? на какие даты или сроки? менеджеры прям за грудки трясут =)

**Comment by dmitrybubyakin** [comment]
@h-zone сейчас там работают все конфиги, которые есть в cropperjs. Могу еще несколько кнопок добавить, если в них есть смысл, как раз думаю насчет aspectRation
![image](https://user-images.githubusercontent.com/11477505/72411141-ef5efa80-3772-11ea-86ff-16684a1bdaf0.png)

**Comment by dmitrybubyakin** [comment]
@h-zone ты сейчас уже можешь пользоваться (кстати, топ фича - работает на edit/create). Думаю в субботу релиз будет, как документацию напишу

**Comment by h-zone** [comment]
@dmitrybubyakin 
мне надо отконфига задать пропорцию с по умоланию растянутой коробкой по максимальной стороне выбранной пропорции, чтобы осталось только таскать коробку по вертикали или горизонтали.

**Comment by dmitrybubyakin** [comment]
@h-zone тут можно это сделать? https://fengyuanchen.github.io/cropperjs/

**Comment by h-zone** [comment]
@dmitrybubyakin
только счас добрался.
плохая дока по `->cropable()`
не ясно, какой `conversion` ему указывать... новый создать? если да, то это, честно говоря лишнее.

**Comment by h-zone** [comment]
коротко-говоря нужны демо-сборки.
счас собрал и не могу добавить изображение

**Comment by dmitrybubyakin** [comment]
@h-zone conversion для crop нужно указывать. spatie/laravel-medialibrary именно так и работает

**Comment by h-zone** [comment]
```php
Medialibrary::make( __( 'Images' ), 'service_images', NovaMedia::class )
->mediaOnIndex( 3 )
->croppable('crop')
->accept( 'image/jpeg', 'image/gif', 'image/png' )
->sortable()
->attachUsing( function ( HasMedia $model, UploadedFile $file, string $collectionName, string $diskName, string $fieldUuid )
{
    if ($model instanceof TransientModel) {
        $collectionName = $fieldUuid;
    }
    $fileAdder = $model->addMedia($file);
    $fileAdder->usingFileName( Str::random( 32 ) . '.' . pathinfo( $file->getClientOriginalName(), PATHINFO_EXTENSION ) );
    $fileAdder->toMediaCollection($collectionName, $diskName);
} )
```
всё верно делаю?

**Comment by dmitrybubyakin** [comment]
@h-zone `Medialibrary::make( __( 'Images' ), 'service_images', NovaMedia::class )` - 3 параметр теперь $diskName

**Comment by h-zone** [comment]
@dmitrybubyakin 
даже вот так в другом ресурсе, использующем медиа нет кнопки "создать" (политик/гейтов нет).
```Medialibrary::make( __( 'Images' ), 'service_images', 'yos' );```
(yos=yandex object storage)
до апа всё работало, естессно

**Comment by h-zone** [comment]
может ли быть, что надо какие-то манипуляции с моделью сделать?
в разделе установка про модель ни слова, на минуточку

**Comment by h-zone** [comment]
если не сложно - покажи свою модельку, которую использовал для работы с филдом.
это бы объяснило многое.

**Comment by dmitrybubyakin** [comment]
```php
<?php declare(strict_types=1);

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Post extends Model implements HasMedia
{
    use HasMediaTrait;

    protected $guarded = [];

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('preview')->singleFile();
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('preview')->width(368)->height(232);

        $this->addMediaConversion('cropped');
    }
}

```

**Comment by h-zone** [comment]
не помогло, у меня так же, только вместо preview -> thumb .
не могу создавать изображения, - нет кнопки "создать".
есть идеи где рыть?

**Comment by dmitrybubyakin** [comment]
@h-zone скинь скрин страницы (если что, создать можно на edit/create, на details нельзя)

**Comment by h-zone** [comment]
не могу скинуть всю страницу. комм.тайна и нда.
может как-то в приват выйти возможно?

**Comment by dmitrybubyakin** [comment]
@h-zone telegram: dmitrybubyakin

**Comment by h-zone** [comment]
кропилка всегда со свободным режимом. невозможно её заставить соблюдать пропорции коробки

**Comment by dmitrybubyakin** [comment]
@h-zone 

https://github.com/dmitrybubyakin/nova-medialibrary-field#attachondetails

![image](https://user-images.githubusercontent.com/11477505/72754647-16815600-3bd1-11ea-9bf2-421e40cec9c8.png)

Насчет 2 и 3 детальнее и если можно, со скринами желаемого результата

**Comment by h-zone** [comment]
@dmitrybubyakin 
1. реально нет кнопок в details
![FireShot Screen Capture #029 - 'ClientArea' - clientarea_h](https://user-images.githubusercontent.com/1150044/72791897-263c8100-3c49-11ea-9312-a1607c3e7fa1.png)

2 и 3:
файл `dmitrybubyakin/nova-medialibrary-field/resources/js/components/Medialibrary/Modals/Cropper.vue`
в кропилке, параметрами указываю aspectRatio и гружу вертикальную фото.
- получаю свободный режим кропилки: скалирования нет, ресайз без учёта пропорций.

**Comment by dmitrybubyakin** [comment]
@h-zone 
![image](https://user-images.githubusercontent.com/11477505/72792797-4157c280-3c42-11ea-8955-350c6fdaad45.png)

Это точно используется?

**Comment by h-zone** [comment]
> 
> 
> @h-zone
> ![image](https://user-images.githubusercontent.com/11477505/72792797-4157c280-3c42-11ea-8955-350c6fdaad45.png)
> 
> Это точно используется?

нет конечно, - пиши на русском инструкцию.

а вообще, есть смысл использовать алгоритм ёonlyOnDetailё и другие аналогичные методы...
из которых после своего кода дёргаешь ёparent::onlyOnDetail()ё
