### ISSUE TITLE
Showing media library field on forms

### ISSUE THREAD

**Issue by Naoray** [dmitrybubyakin/nova-medialibrary-field#3]
First of all: Thanks for this field :)!!

Regarding my issue:
`Medialibrary field is shown only on index and details views. If there is any reason to show it on forms, let me know.`

=> it is confusing to have to click on the detail view in order to edit media fields on a resource...

It would feel so much more intuitive to just be able to click on the edit btn and be able to edit/add media files.

**Comment by dmitrybubyakin** [comment]
@Naoray What if you would use the HasMany field? There would be a table with media on the detail view. So `Medialibrary` field allows you display your media files in a field instead of a panel with table (it's like on index view).

**Comment by Naoray** [comment]
Not sure if I get it. So you are saying using hasMany results in the same as using the medialibrary field, because both require to view the detail view in order to edit those?

**Comment by dmitrybubyakin** [comment]
@Naoray Yes.

**Comment by Naoray** [comment]
true that
