### ISSUE TITLE
What about forms?

### ISSUE THREAD

**Issue by programmende** [dmitrybubyakin/nova-medialibrary-field#30]
> What about forms?
> Medialibrary field is shown only on index and details views. If there is any reason to show it on forms, let me know.

The reason is, because i create a shop and when i adding a product, i will upload images direct from froms instead of safe the form, go to details and upload images then :-)

**Comment by dmitrybubyakin** [comment]
@programmende I'll do it.

**Comment by sijones-uk** [comment]
This would be really useful for me too. I'm using the media library to store the avatar for a user, so when the user record is edited in Nova it's logical to be able to change the avatar on the edit form. (As an aside, is it possible to limit the number of media items associated with a resource? I want to restrict the number of avatars per user to 1.)

**Comment by dmitrybubyakin** [comment]
@sijones-uk https://github.com/dmitrybubyakin/nova-medialibrary-field#single-media-collection

**Comment by sijones-uk** [comment]
I didn't spot that - thanks!
