### ISSUE TITLE
Возможно бага

### ISSUE THREAD

**Issue by h-zone** [dmitrybubyakin/nova-medialibrary-field#31]
На Нове 2.4.0 не удаляются загруженные изображения.
Прошу проверить функциональность.

при этом новые файлы грузятся и удаляются

**Comment by h-zone** [comment]
вообще никаких действий произвести нет возможности со старыми файлами, залитыми ранее новы 2.4.0

**Comment by dmitrybubyakin** [comment]
@h-zone Выложил новую версию
