### ISSUE TITLE
Detail links not working 

### ISSUE THREAD

**Issue by shazibrazzaq** [dmitrybubyakin/nova-medialibrary-field#32]
![image](https://user-images.githubusercontent.com/7521588/66759906-89847d80-eeba-11e9-8313-6848b77891f6.png)

Can you please confirm why they are not working in upgraded version of 2.4.0

**Comment by h-zone** [comment]
confirm, at nova 2.4.0 not works

**Comment by shazibrazzaq** [comment]
@dmitrybubyakin any help?

**Comment by cfreak** [comment]
also confirm that on my installation with nova 2.3.1

**Comment by shazibrazzaq** [comment]
I think this is the problem, if someone with Vue knowledge can help

vendor/dmitrybubyakin/nova-medialibrary-field/resources/js/components/Medialibrary/File/FileAction.vue

this.$emit('view') is not wokring. $emit is not working.

**Comment by webparadoxer** [comment]
same problem

**Comment by dmitrybubyakin** [comment]
Working on fix

**Comment by cfreak** [comment]
Maybe the hints are helping :-)

**Comment by cfreak** [comment]
#35 Pull Request for these two problems

**Comment by shazibrazzaq** [comment]
@dmitrybubyakin as you are fixing, keep an eye on this too

![image](https://user-images.githubusercontent.com/7521588/66838451-1fcda780-ef7e-11e9-86e3-a96a14dd2092.png)

**Comment by shazibrazzaq** [comment]
it's still not working, can you please confirm you tested it with nova 2.4.0?

**Comment by dmitrybubyakin** [comment]
@shazibrazzaq Yes, I'm using the last version of Nova. Same error?

**Comment by shazibrazzaq** [comment]
Yes exactly same error.. emit not triggering

**Comment by dmitrybubyakin** [comment]
@shazibrazzaq emit always triggers, do you have any logs?

**Comment by dmitrybubyakin** [comment]
@shazibrazzaq Could you check it now? https://github.com/dmitrybubyakin/nova-medialibrary-field/releases/tag/1.2.1

**Comment by shazibrazzaq** [comment]
sort works, upload works but those buttons didn't work again. I even tried removing the old version and then install again after clearing cache.

**Comment by dmitrybubyakin** [comment]
@shazibrazzaq can't reproduce

**Comment by shazibrazzaq** [comment]
@dmitrybubyakin i thank you a lot for helping.

I am not sure why it's not working. Here is the video it even doesn't give any error in console. Also in tried running npm run watch and see on file 
vendor/dmitrybubyakin/nova-medialibrary-field/resources/js/components/Medialibrary/File/FileAction.vue

the functions are working but this.$emit is not.

**Comment by shazibrazzaq** [comment]
thank you i will configure it and test and let you know the results. @dmitrybubyakin

**Comment by shazibrazzaq** [comment]
@dmitrybubyakin i tried it with new instance with nova 2.5 and Laravel 6 it worked like a charm. I think there is something wrong with my app i tried npm run watch while it was not working i think there is something in cache. I will figure it out and let you know. Thanks a lot for your help it worked well in new app.
