### ISSUE TITLE
Edit Link not Working

### ISSUE THREAD

**Issue by cfreak** [dmitrybubyakin/nova-medialibrary-field#33]
Hi,

i'm using Nova 2.3.1 and the Edit-Links are not working.

It seems that everything is fine, and there is no error, event the ajax request seems correct, but the fields are not showing up. Also the Event-Name seems wired to me.

Do you have any Idea why?

Best Regards
Max

Attached a Screenshot:
<img width="1602" alt="Bildschirmfoto 2019-10-15 um 13 54 48" src="https://user-images.githubusercontent.com/202342/66829292-60fc9200-ef53-11e9-9719-d380fff3ba53.png">

**Comment by dmitrybubyakin** [comment]
@cfreak Fixed
