### ISSUE TITLE
Change "Choose Files" button text to "Choose File" when using ->singleFile() collection

### ISSUE THREAD

**Issue by scottgrayson** [dmitrybubyakin/nova-medialibrary-field#37]
When using
https://laravelpackages.net/dmitrybubyakin/nova-medialibrary-field#single-media-collection

Button text should change to "Choose File" Instead of "Choose Files"

related question: Is there a method to customize the button text?

**Comment by dmitrybubyakin** [comment]
@scottgrayson You can use your own translations. https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/resources/js/components/Medialibrary/UploadFiles.vue#L25

**Comment by scottgrayson** [comment]
@dmitrybubyakin Thanks. This solves my problem for now, but It would not help if i needed to use a single file collection on one resource and a multiple file collection on another
