### ISSUE TITLE
Ability to use different Storages

### ISSUE THREAD

**Issue by h-zone** [dmitrybubyakin/nova-medialibrary-field#38]
Hi!

Case: need ability to store to the S3 compatible storage: Amazon/Yandex/DO

It is possible to operate with `toMediaCollection()` in this project?

Any advise?

**Comment by dmitrybubyakin** [comment]
@h-zone Hi. 
https://github.com/dmitrybubyakin/nova-medialibrary-field#usage
https://github.com/dmitrybubyakin/nova-medialibrary-field#store-and-replace-callbacks
https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/src/Http/Controllers/StoreMedia.php#L32

**Comment by h-zone** [comment]
Дим.
Дам идею, а ты думай...
У библиотеки есть возможность регистрировать прямо в модели коллекции в виде?
```
    public function registerMediaCollections()
    {
        $this->addMediaCollection('public');
        $this->addMediaCollection('yos');
    }
```
Может есть смысл поправить твой код таким образом, чтобы оно смотрелов `$this->mediaCollections`  модели ??

Это по сути в несколько строк снимает необходимость кодить тонну строк и придаёт пакету буст среди конкурентов. хотя какие тут конкуренты...

**Comment by h-zone** [comment]
и да, твои ттыски не объясняют. они ещё сильнее путают.

**Comment by dmitrybubyakin** [comment]
@h-zone Ты можешь использовать любую коллекцию и так. Этот пакет всего-лишь обертка, над `spatie/laravel-medialibrary`. Чтобы грузить файлы на S3 - достаточно указать диск - https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections/#using-a-specific-disk

**Comment by dmitrybubyakin** [comment]
@h-zone `У библиотеки есть возможность регистрировать прямо в модели коллекции в виде?` - нет, это ответственность разработчика

**Comment by dmitrybubyakin** [comment]
Т.е. ты сам там можешь написать этот код в модели

**Comment by h-zone** [comment]
либо я пропустил в спешке, либо ты не прочёл. не суть важно.
- мне необходимо класть в 3 коллекции: локальную, и два сторонних облака: aws+яндекс.

**Comment by h-zone** [comment]
но я понял тебя. попробую сделать вкладыш в твою обёртку ))

**Comment by dmitrybubyakin** [comment]
@h-zone насколько знаю, у файла может быть только одна коллекция - https://github.com/spatie/laravel-medialibrary/blob/master/database/migrations/create_media_table.php.stub#L17

**Comment by dmitrybubyakin** [comment]
Так же, обрати внимание на events - https://github.com/spatie/laravel-medialibrary/tree/master/src/Events, может натолкнет на нужную мысль

**Comment by h-zone** [comment]
ну да... всё так.

коллекция может быть одна, локальная.

однако вот:

https://github.com/spatie/laravel-medialibrary/blob/5b123abfd4c8560421e6a45ef25086a1f188399c/src/HasMedia/HasMediaTrait.php#L31

и

https://github.com/spatie/laravel-medialibrary/blob/5b123abfd4c8560421e6a45ef25086a1f188399c/src/HasMedia/HasMediaTrait.php#L449

**Comment by dmitrybubyakin** [comment]
@h-zone В модели их может быть сколько угодно, но при добавлении файлы ты выбираешь одну их них, а не все сразу

**Comment by h-zone** [comment]
https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/working-with-multiple-filesystems/

**Comment by dmitrybubyakin** [comment]
@h-zone disk_name можно указать тут https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections/#single-file-collections

**Comment by h-zone** [comment]
по другому постучу в дверку:

файл: `dmitrybubyakin/nov~medialibrary-field/src/Http/Controllers/StoreMedia.php`
метод `__invoke`
контекст: в конце return
если от конфы расширить функционал, то будет круто.
в противном случае в `storeUsing()` сначала кладём в облако, потом локально, сугубо логически должно быть наоборот и работать с облаком, если файл локально лёг, а может не лечь, ибо некоторые jpeg миме оно просто не узнаёт.

**Comment by h-zone** [comment]
я могу pullRequest попробовать накидать, если обещаешь сегодня-завтра посмотреть.

**Comment by dmitrybubyakin** [comment]
@h-zone так, что-то ты меня запутал. Какая задача?

**Comment by h-zone** [comment]
>
> 
> либо я пропустил в спешке, либо ты не прочёл. не суть важно.
> 
>     * мне необходимо класть в 3 коллекции: локальную, и два сторонних облака: aws+яндекс.

**Comment by dmitrybubyakin** [comment]
@h-zone локальная в приоритете?

**Comment by h-zone** [comment]
локальная - обязательно. это исходный бэкап.
все внешние - источники для клиентов.

при этом надо как-то дать понять локальной файловой системе, что 650 000 файлов в одной папке - зло неимоверное.
тут xfs/riser не спасут ничерта.

**Comment by h-zone** [comment]
в догонку.
надо как-то регистрировать файлы таким образом в базе, чтобы можно было найти записи с битыми файлами и файлы без записей. реально ногу сломать можно видя, как `ls` смотрит в папку с 650 000 директориями/файлами - 3 минуты чтения директории.

**Comment by h-zone** [comment]
то есть нужен механизм чистки/информирования об орфанах (orphaned record)

**Comment by dmitrybubyakin** [comment]
@h-zone используй medialibrary для добавления файла локально (то как они хранятся можно настраивать, смотри документацию medialibrary). Для всего остального - повесь listeners на добавление/удаление файла в нужные коллекции. И будет тебе нужный порядок

**Comment by dmitrybubyakin** [comment]
@h-zone В общем, если ответ выше тебя не устроит - пришли PR, как ты видишь решение проблемы. Если будет что-то полезное там, то добавлю

**Comment by h-zone** [comment]
хорошо, закрывай топик

**Comment by h-zone** [comment]
так.
эвенты не прокатывают, ибо уйдут в цикл от MediaHasBeenAdded
так как в листенере
```
<?php
namespace App\Listeners;
use Spatie\MediaLibrary\Events\MediaHasBeenAdded;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
class MediaHasBeenAddedListener
{
    public function __construct()
    { }
    public function handle(MediaHasBeenAdded $event)
    {
        $media          = $event->media;
        $path           = $media->getPath();
        $model          = ( new $media->model_type )->find( $media->model_id );
        $model->addMedia( $path )->toMediaCollection( $collectionName, 's3' );
    }
```
`addMedia()` зациклит всё.

через Observers не красиво, но работать будет, однако и там будет зациклен observer так как надо добавить запись в бд о файле на другом диске.

короче куда не глянь - подводный камень.

**Comment by h-zone** [comment]
как вариант "грязная запись", кладём в s3 файл без упоминания где-либо.
работаем от локального имени файла, и опять же, "грязно" удаляем из облака по имени файла.

всё не красиво...

**Comment by dmitrybubyakin** [comment]
@h-zone можно игнорировать `s3` и не будет зацикливания.
```php

public function handle(MediaHasBeenAdded $event)
{
    if ($event->media->collection_name !== 'local') {
        return;
    }
    // ...
}
```

**Comment by h-zone** [comment]
у меня философия.
-- если 2 подобных патча - писать проект заново.

**Comment by h-zone** [comment]
@dmitrybubyakin 
Обнаружил, что:

1. нова не использует событий моделей и/или слушателей. Поэтому оно тут вообще не к месту.
https://github.com/laravel/nova-issues/issues/912#issuecomment-434943954
davidhemphill заявляет, что это фича.
ладно, Бог с ним.

2. работая от обсервера, выявил, что рнр-скрипт работает быстрее, чем появляется файл физически. Соответственно дёргать события вручную из обсервера не получится тоже.

3. дёргать вручную листенер, это как дёргать за те самые места, ожидая фантастического результата. короче не красиво получается.

Осталось 4 варианта решения проблемы:

а) дописывать филду. идеальный.
б) писать Job. категорически некомильфо.
в) использовать только один диск за один раз.
г) использовать медиабиблиотеку 2 раза - 2 филда, смотрящие в разные диски.

есть рекомендации?
