### ISSUE TITLE
ability to to edit media on update/create

### ISSUE THREAD

**Issue by AbanoubNassem** [dmitrybubyakin/nova-medialibrary-field#39]
consider your `cpanel/admin` will be accessed by some employees, so they should be able to update/create media , through the create/update forms , because it's confusing to go in the `view` view in order to edit the media  , currently when enabled on `update/create` views using `showOnUpdating/showOnCreating` it shows this :-

![Screen Shot 2019-12-09 at 11 00 10 AM](https://user-images.githubusercontent.com/13698722/70414294-1a1eaa80-1a73-11ea-9353-edd59b5a0f71.png)

any suggestions ?

**Comment by dmitrybubyakin** [comment]
@AbanoubNassem I'll do it

**Comment by AbanoubNassem** [comment]
@dmitrybubyakin , much appreciated , any clue how long would it take to be done ?

**Comment by dmitrybubyakin** [comment]
@AbanoubNassem I'll try to release a new version in Jan

**Comment by h-zone** [comment]
@dmitrybubyakin cool stack ))
will try in about 2-3 days.
good job!
