### ISSUE TITLE
.webp/.webm support

### ISSUE THREAD

**Issue by h-zone** [dmitrybubyakin/nova-medialibrary-field#41]
If in my set of images/videos present `.web*` file, i see at index list of links instead of `<img` presentation

I ask to add support for .webp / .webm formats.

Thanks a lot!

**Comment by dmitrybubyakin** [comment]
@h-zone Hi. Try using:
```php
Medialibrary::make('Featured Image', 'featured')
    ->imageMimes('image', 'mimes', 'that', 'you', 'need')
    ->thumbnail(...)
```

**Comment by h-zone** [comment]
its not helps me.
im usint mimes of png, jpeg, gif, but webp uploadable anyway
adding the webp to the list will not solve problem
