### ISSUE TITLE
Questions regarding customization

### ISSUE THREAD

**Issue by spekulatius** [dmitrybubyakin/nova-medialibrary-field#42]
Hello @dmitrybubyakin 

thanks for providing this great module for Nova! I was wondering if you could help me out understanding it a bit more. I've fiddled around a bit but I'm still wondering if / how it's possible to do these two things:

- Add the image to the "Media Details" modal and
- Making the image regular square (not rounded) in the index list

Peter

**Comment by dmitrybubyakin** [comment]
@spekulatius Hi. 
 - https://github.com/dmitrybubyakin/nova-medialibrary-field#installation
 - https://github.com/dmitrybubyakin/nova-medialibrary-field#custom-media-resource
`Making the image regular square (not rounded) in the index list` - you can override this file https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/resources/js/components/IndexField.vue#L5

Also I'm going to release a new version in a few days with new features.

**Comment by spekulatius** [comment]
Hello @dmitrybubyakin 

thanks for getting back to me. How would one go to overwrite the IndexField without having an own compontent (just using the one which has the media trait itself).

Cheers,
Peter

Btw, I've got two minor changes I'll open a PR for soon - it's just something to consider for the next release.

**Comment by dmitrybubyakin** [comment]
@spekulatius Hello.

> How would one go to overwrite the IndexField without having an own component

I'll add the ability to add your custom classes to the image on the index view. I'll do it right after the release.

**Comment by spekulatius** [comment]
Cool, thanks @dmitrybubyakin
