### ISSUE TITLE
Crop problem and custom field

### ISSUE THREAD

**Issue by renanpicanco** [dmitrybubyakin/nova-medialibrary-field#46]
Laravel 6.x
Nova: 2.9.3

Crop:

- After selecting the cropping area, the image remains unchanged.
- How to perform a correct configuration for this feature to work correctly?
- Which steps I need to follow?

Custom field
- It's possible to add a custom field on modal of title/description?

**Comment by dmitrybubyakin** [comment]
@renanpicanco Hi.

> It's possible to add a custom field on modal of title/description?

Yes, you can use the [fields](https://github.com/dmitrybubyakin/nova-medialibrary-field#fields) method.

> After selecting the cropping area, the image remains unchanged.

Could you share your field configuration and maybe video or gif?

**Comment by renanpicanco** [comment]
Hi @dmitrybubyakin.

Thanks for the answer and congratulations for excellent job on Medialibrary Field, this help-me so much.

About your questions.

> Could you share your field configuration and maybe video or gif?

`Medialibrary::make('Media')
                ->croppable('cropped')
                ->attachExisting(),`

![crop](https://user-images.githubusercontent.com/2030735/73067720-2ffff780-3e88-11ea-8def-1687671c637f.gif)

**Comment by dmitrybubyakin** [comment]
@renanpicanco do you use queues?

**Comment by renanpicanco** [comment]
@dmitrybubyakin no!

**Comment by dmitrybubyakin** [comment]
@renanpicanco do you have the `cropped` conversion in your model?

**Comment by renanpicanco** [comment]
@dmitrybubyakin no, maybe it's the problem. Where I can see this example code?

**Comment by dmitrybubyakin** [comment]
In your model should be something like this:

```php
public function registerMediaConversions(Media $media = null): void
{
    $this->addMediaConversion('cropped');
}
```

**Comment by dmitrybubyakin** [comment]
Medialibrary doesn't change the original file. All manipulations are performed on defined conversions

**Comment by renanpicanco** [comment]
Ok, but how do I see the cut file and use it?

**Comment by dmitrybubyakin** [comment]
@renanpicanco 
![image](https://user-images.githubusercontent.com/11477505/73068528-1ffe0d00-3eb4-11ea-8d16-d8856fe9ea0b.png)

**Comment by renanpicanco** [comment]
@dmitrybubyakin 

- It's possible to set a cropped image as a selected on field?
- When I want to make more than one conversion, it's has a default logic?

Maybe It's good to add more information about what the croppable works for help others..

**Comment by dmitrybubyakin** [comment]
@renanpicanco try `previewUsing ('cropped')`

**Comment by dmitrybubyakin** [comment]
@renanpicanco 

> When I want to make more than one conversion, it's has a default logic?

You can have more than one conversion, but right now only one conversion can be croppable.

https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/storing-media-specific-manipulations/#storing-media-specific-manipulations

**Comment by renanpicanco** [comment]
@dmitrybubyakin thanks.
