### ISSUE TITLE
Using with nova-flexible-content

### ISSUE THREAD

**Issue by moritzlang** [dmitrybubyakin/nova-medialibrary-field#47]
Hi!

Thank you for your work on this field!

When using nova-medialibrary-field inside the flexible field content this error gets thrown:
`Field '9cc2fa43048f71a6__media' is not found. In case you are using Panel or Field which contains Medialibrary field, check out DmitryBubyakin\NovaMedialibraryField\MedialibraryFieldResolver::using() method`

How can I use the nova-medialibrary field together with nova-flexible-content / How can I set up the resolver?

Thank you for your help!

**Comment by dmitrybubyakin** [comment]
@moritzlang Hi. nova-flexible-content is not supported

**Comment by dmitriytretyakov** [comment]
А можешь подсказать в какую сторону копать, чтобы хоть как-то заработало?

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov nova-flexible-content никак не заработает с текущей версией, можно посмотреть в строну `epartment/nova-dependency-container`, с ним работает.

**Comment by dmitriytretyakov** [comment]
Не, там ведь другой функционал. Я делаю блочный редактор статей и несколько блок используют изображения, а nova-dependency-container просто показывает поле в зависимости от условия.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Пока что сложно добавить поддержку для `nova-flexible-content`, т.к. там все хранится в json и сложно привязать media к json-объекту.

**Comment by dmitriytretyakov** [comment]
Так можно же в json хранить только ID медиа, а сам media хранить в той же таблице, что и остальные изображения. Разве нет?

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov разные варианты есть, но нужно время, у меня пока что его мало. Если есть возможность, был бы рад увидеть прототип и мог бы от него отталкиваться.

**Comment by dmitriytretyakov** [comment]
Я поэтому и спросил, есть ли мысль в какую сторону искать решение? Просто я не писал своих решений для Nova, но хотел бы помочь с этим функционалом.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Нужно каким-то образом связать модель Media с json объектом. Попробую со своей стороны здесь что-то завтра сделать.

**Comment by dmitriytretyakov** [comment]
Хорошо. Если не сложно, напиши потом чем дело кончится, даже если не получится, а то проект не могу сдать без этого) Так-то классное у тебя решение, не хочется отказываться из-за такой фигни, но и flexible удобная штука, которой многие пользуются.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Привет, v2 сейчас можно использовать с nova-flexible-content, можешь протестировать как будет возможность? Чтобы все нормально заработало, нужно чтобы приняли PR здесь - https://github.com/whitecube/nova-flexible-content/pull/165, а пока что в тестовых целях можно использовать форк.

`composer.json`

```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/dmitrybubyakin/nova-flexible-content"
        },
        {
            "type": "git",
            "url": "https://github.com/dmitrybubyakin/nova-medialibrary-field"
        }
    ],
    "require": {
        "whitecube/nova-flexible-content": "dev-master",
        "dmitrybubyakin/nova-medialibrary-field": "v2.x-dev"
    },
}
```

`App\Providers\NovaServiceProvider`

```php
use DmitryBubyakin\NovaMedialibraryField\Bridge\Flexible\FlexibleMedialibraryFieldResolver;

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    public function boot()
    {
        parent::boot();

        MedialibraryFieldResolver::using(new FlexibleMedialibraryFieldResolver);
    }
}
```

`App\Nova\Post`

```php
use DmitryBubyakin\NovaMedialibraryField\Bridge\Flexible\MedialibraryFieldLayout;

class Post extends Resource
{
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Flexible::make('Content')
                ->addLayout(new MedialibraryFieldLayout('Simple content section', 'wysiwyg', [
                    Text::make('Title'),
                    Markdown::make('Content'),
                    Medialibrary::make('Content Media')->attachRules('image', 'dimensions:min_width=500,min_height=500'),
                ]))
                ->addLayout(new MedialibraryFieldLayout('Video section', 'video', [
                    Text::make('Title'),
                    Markdown::make('Content'),
                    Medialibrary::make('Video Cover')->single(),
                ])),

            Medialibrary::make('Cover')->single(),
        ];
    }
}
```

У Medialibrary поле attribute должно быть уникальным, в противном случае, будет использоваться первый попавшийся вариант.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Все Media добавляются к ресурсу с которым работаешь, те что внутри Flexible - добавляется `custom_properties->flexibleKey`, по нему и фильтруется все с помощью `Medialibrary::resolveMediaUsing`.

**Comment by dmitriytretyakov** [comment]
Привет! Огромное спасибо, я в понедельник обязательно проверю и отпишусь

**Comment by dmitriytretyakov** [comment]
Супер! Почти работает.

1. Если добавить ->rules('required'), то даже при загруженном ошибке выдает ошибку, что поле пустое.
2. В режиме создания изображение корректно загрузилось, появилось в таблице media, но при переходе в режим редактирования или просмотра изображение не загрузилось. Посмотрел код и запросы, похоже ключ.

Подробнее:: 
- При создании в таблицу изображение сохранилось с flexibleKey = "b3w32yhdhqmeempjk3z7lp-image"
- После сохранения открываю страницу просмотра и в консоли вижу запрос "/nova-vendor/dmitrybubyakin/nova-medialibrary-field/articles/4/media/95cf55fe4b48b702__%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5?fieldUuid=4f4237b1-00f6-493b-83c0-e323d186a2c5", , но изображения с ключом 95cf55fe4b48b702 понятное дело не находит.

При переходе в режим редактирования выполняется такой же запрос.

Первая мысль была такая: 
Похоже что этот ключ меняется только после создания сущности. Не знаю с чем это связано, но рискну предположить, что на генерацию ключа влияет ID сущности.

Попробовал удалить блок и заново создать уже в режиме редактирования, ведь ID сущности уже установлен, в базу сохранился как "jy26n8xeuw94lxwewzsrwk-image", а после сохранения запрос "nova-vendor/dmitrybubyakin/nova-medialibrary-field/articles/4/media/9fd1477183bec20b__%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5?fieldUuid=331a69f7-86f4-4376-b323-d4c337ee8191" сломал эту догадку.

Далее попробовал в режиме редактирования не удалять блок, а просто загрузить новое изображение. В этом случае всё работает корректно.

Если посмотреть таблицу где хранится сама сущность и её JSON с содержанием блоков, то там тоже хранится 9fd1477183bec20b

Получается проблему можно описать так:

1. При создании нового блока, flexibleKey принимает некорректное значение, а если блок существовал в момент получения данных сущности, то проблема не проявляется.

Наверное для тебя, как для разработчика этого решения, это очевидные вещи, просто пытаюсь помочь разобраться)

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Привет, насчет details view, у тебя точно эта версия `https://github.com/dmitrybubyakin/nova-flexible-content:dev-master`?

**Comment by dmitriytretyakov** [comment]
Да, вот мой composer
```
"repositories": [
        {
            "type": "path",
            "url": "./nova"
        },
        {
            "type": "git",
            "url": "https://github.com/dmitrybubyakin/nova-flexible-content"
        },
        {
            "type": "git",
            "url": "https://github.com/dmitrybubyakin/nova-medialibrary-field"
        }
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "alexbowers/nova-prepopulate-searchable": "^1.0",
        "benjaminhirsch/nova-slug-field": "^1.2",
        "caouecs/laravel-lang": "~5.0",
        "coderello/laravel-nova-lang": "^1.3",
        "dmitrybubyakin/nova-medialibrary-field": "v2.x-dev",
        "epartment/nova-dependency-container": "^1.2",
        "fideloper/proxy": "^4.0",
        "froala/nova-froala-field": "^3.2",
        "fruitcake/laravel-cors": "^1.0",
        "genealabs/nova-map-marker-field": "^0.1.15",
        "johnathan/nova-trumbowyg": "^1.0",
        "laravel/framework": "^7.0",
        "laravel/nova": "~3.0",
        "laravel/tinker": "^2.0",
        "naxon/nova-field-sortable": "^1.0",
        "sloveniangooner/searchable-select": "^1.3",
        "spatie/eloquent-sortable": "^3.7",
        "spatie/laravel-medialibrary": "^7.0.0",
        "tanmuhittin/nova-collapsible-groups": "^0.3.0",
        "teamtnt/laravel-scout-tntsearch-driver": "^8.1",
        "techouse/intl-date-time": "^1.4",
        "titasgailius/search-relations": "^1.0",
        "whitecube/nova-flexible-content": "dev-master"
    },
```

Или whitecube/nova-flexible-content нужно было заменить на dmitrybubyakin/nova-flexible-content?

**Comment by dmitrybubyakin** [comment]
`whitecube/nova-flexible-content` нужно заменить на `dmitrybubyakin/nova-flexible-content`. Запушил фикс для валидации.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov сейчас проверил со своей стороны - работает валидация и показывает на edit/details без проблем.

**Comment by dmitriytretyakov** [comment]
А почему удалил сообщение про замену пакета на твой?

**Comment by dmitrybubyakin** [comment]
@moritzlang не так понял то что ты написал. Должно все быть в точности, как я писал в примере выше.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov У тебя все ок с composer.json

**Comment by dmitriytretyakov** [comment]
- Updating dmitrybubyakin/nova-medialibrary-field v2.x-dev (e013bb6 => 3feea8f):  Checking out 3feea8f495

Забрал коммит, попробовал снова - ничего не изменилось.

По пунктам
1. Перехожу на страницу создания сущности, добавляю блок, в котором содержится изображение, загружаю его.
2. Сохраняю сущность
3. После сохранения попадаю на страницу просмотра, там пусто, на странице редактирования тоже

**Comment by dmitriytretyakov** [comment]
В DetailField изменение присутствует.

**Comment by dmitriytretyakov** [comment]
Валидация кстати заработала.

**Comment by dmitriytretyakov** [comment]
Посмотрел внимательно, оказывается ты используешь MedialibraryFieldLayout, а его не заметил. Сейчас попробую

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov проверь чтобы везде были актуальные изменения, т.к. такой вариант у меня прекрасно работает:

```php
<?php

namespace App\Nova;

use DmitryBubyakin\NovaMedialibraryField\Bridge\Flexible\MedialibraryFieldLayout;
use DmitryBubyakin\NovaMedialibraryField\Fields\Medialibrary;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Markdown;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;
use Whitecube\NovaFlexibleContent\Flexible;

class Post extends Resource
{
    public static $model = \App\Post::class;

    public static $title = 'id';

    public static $search = [
        'id',
    ];

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Flexible::make('Content')
                ->addLayout(new MedialibraryFieldLayout('Simple content section', 'wysiwyg', [
                    Text::make('Title'),
                    Markdown::make('Content'),
                    Medialibrary::make('Content Media')->attachRules('image', 'dimensions:min_width=500,min_height=500'),
                ]))
                ->addLayout(new MedialibraryFieldLayout('Video section', 'video', [
                    Text::make('Title'),
                    Markdown::make('Content'),
                    Medialibrary::make('Video Cover')->rules('required')->single(),
                ])),

            Medialibrary::make('Cover')->single(),
        ];
    }
}

```

**Comment by dmitriytretyakov** [comment]
Да, теперь заработало. Большое тебе спасибо :) Дам знать если еще какой-то баг поймаю, но на первый взгляд всё ок

**Comment by dmitriytretyakov** [comment]
Кажется нашел баг, если атрибуты будут разные, но названия одинаковые, то происходит та же проблема что и если бы атрибуты были одинаковыми. Попробуй в свое примере заменить 
Medialibrary::make('Content Media') на Medialibrary::make('Изображение', 'content_media') и Medialibrary::make('Video Cover') на Medialibrary::make('Изображение', 'video_cover')

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov `Medialibrary::make($name = $attribute, $collectionName)`. Позже сделаю чтобы можно было кастомизировать эти поля.

**Comment by dmitriytretyakov** [comment]
Ну вообще вариант ($name,  $attribute, $collectionName) работает как надо, в таблицу media попадает именно $attribute, а на экране именно $name, проблема только в конфликте двух одинаковых названий.

**Comment by dmitrybubyakin** [comment]
@dmitrybubyakin Сейчас как ты написал не работает. https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/v2/src/Fields/Medialibrary.php#L55

**Comment by dmitriytretyakov** [comment]
Вот реальный пример, у меня сохраняет в базу как single_image
```
Medialibrary::make('Одно изображение', 'single_image', 'medialibrary')->rules(['required'])->previewUsing('thumb')->croppable('cropped')->single()->attachExisting()->fields(function () {
                    return [
                        Text::make('Имя файла', 'name')
                            ->rules('required', 'min:2'),
                        Text::make('Alt атрибут', 'custom_properties->alt'),
                        Text::make('Title атрибут', 'custom_properties->title'),
                    ];
                }),
```

**Comment by dmitriytretyakov** [comment]
Кажется еще баг:
1) Создал блок типа А, в нем загрузил изображение, сохранил сущность, всё ок.
2) Вернулся в режим редактирования, создал еще блок типа А, загрузил изображение туда, сохранил сущность.

В итоге во втором блоке изображение есть, а в первом исчезло, будто бы я заменил одно на другое.

P.S. Блок типа А использует метод single()

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov `Medialibrary::make('Одно изображение', 'single_image', 'medialibrary')` получается: `name = attribute = Одно изображение, collection_name = single_image, disk_name = medialibrary`, верно?

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov `Medialibrary::single()` применяется к коллекции

**Comment by dmitriytretyakov** [comment]
1. Да, верно. В таблице collection_name, а attribute ведь нигде не используется получается... понял тебя, буду ждать фикс.
2. Что значит к коллекции, а не к field?

**Comment by dmitriytretyakov** [comment]
Вот пример блока, на котором проявляется ситуация с удалением изображения
```
 ->addLayout('Планировка', 'apartment_layout', [
                Medialibrary::make('Изображение планировки', 'apartment_layout_image', 'medialibrary')->rules(['required'])->previewUsing('thumb')->croppable('cropped')->single()->attachExisting()->fields(function () {
                    return [
                        Text::make('Имя файла', 'name')
                            ->rules('required', 'min:2'),
                        Text::make('Alt атрибут', 'custom_properties->alt'),
                        Text::make('Title атрибут', 'custom_properties->title'),
                    ];
                }),
                Text::make('Количество комнат', 'rooms_count')->rules(['required', 'max:1']),
                Number::make('Площадь', 'area')->rules(['required'])->step(0.1),
                Number::make('Стоимость', 'price')->rules(['required']),
                Textarea::make('Описание', 'description')
            ])
```

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections/#single-file-collections

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov добавлю возможность указать attribute (будет метод `Medialibrary::make()->usingAttribute()`, в след. версии перенесу в конструктор)

**Comment by dmitriytretyakov** [comment]
@dmitrybubyakin я использую singleFile
`
$this->addMediaCollection('apartment_layout_image')->singleFile()
`, но баг всё равно есть.  Также при загрузке во второй блок, в первом изображение пропадает, наверное из-за совпадающих имен полей, но я ведь на это не могу повлиять раз блок один и тот же.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov файл пропадает, т.к. у них одна коллекция

**Comment by dmitriytretyakov** [comment]
И что делать?)

**Comment by dmitrybubyakin** [comment]
@dmitrybubyakin я не слишком понимаю контекст задачи.

**Comment by dmitriytretyakov** [comment]
@dmitrybubyakin Смотри, flexible что дает? Создавать контент из разных блоков, при этом каждый блоки можно добавлять произвольное количество раз. В моём примере я делаю редактор материалов и там есть блок "Планировка", в материале может быть несколько планировок.

В чём проблема: я добавлю первый блок планировки, гружу изображение и сохраняю. Пока всё хорошо, потом я добавляю еще одну планировку, используя ту же самую конфигурацию блока планировки. И вот тут баг: в первой планировке после сохранения пропадает изображение.

Понятно объяснил?)

**Comment by dmitriytretyakov** [comment]
Прости, это был мой косяк, всё из-за singleFile(), я его отключил, а у поля добавил single() и всё заработало как нужно.
