### ISSUE TITLE
my media model is other database name

### ISSUE THREAD

**Issue by MilesWuCode** [dmitrybubyakin/nova-medialibrary-field#48]
can i setting ?

use Spatie\MediaLibrary\Models\Media as Model;

class Media extends Model
{
    protected $connection = 'other_db';
}

**Comment by MilesWuCode** [comment]
config/medialibrary.php
    'media_model' => Spatie\MediaLibrary\Models\Media::class,

**Comment by dmitrybubyakin** [comment]
@MilesWuCode Hi, I think you should ask this question [here](https://github.com/spatie/laravel-medialibrary/issues)

**Comment by MilesWuCode** [comment]
class Media extends Resource
{
    public static $model = 'Spatie\MediaLibrary\Models\Media';

to change custom !!

public static $model =  config('medialibrary.media_model');

**Comment by dmitrybubyakin** [comment]
@MilesWuCode Can't understand you. What is your native language?

**Comment by MilesWuCode** [comment]
class FieldServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Media::$model = config('medialibrary.media_model');

i need custom medialibrary model 
custom medialibrary model is connect other database server
