### ISSUE TITLE
when other database.media table only upload files, delete & edit not work

### ISSUE THREAD

**Issue by MilesWuCode** [dmitrybubyakin/nova-medialibrary-field#49]
This is great plugin !! nice job!

in my case :

- i have two databases

- nova web connect A db

- B db has media table

```php
namespace App\Models;
//...
use Spatie\MediaLibrary\Models\Media as Model;

class Media extends Model
{
   protected $connection = 'B db';
```

- config/medialibrary.php

```php
    /*
     * The disk on which to store added files and derived images by default. Choose
     * one or more of the disks you've configured in config/filesystems.php.
     */
    'disk_name' => env('MEDIA_DISK', 'public'),

    // ....

    /*
     * The fully qualified class name of the media model.
     */
    'media_model' => App\Models\Media::class,
```

nova-medialibrary-field 

- can upload file
- can not delete
- can not edit

show error : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'A.media' doesn't exist

**Comment by dmitrybubyakin** [comment]
@MilesWuCode Do you use your model inside a resource?

**Comment by MilesWuCode** [comment]
> @MilesWuCode Do you use your model inside a resource?

Yes

**Comment by dmitrybubyakin** [comment]
@MilesWuCode Fixed. Could you check it out?

**Comment by MilesWuCode** [comment]
> @MilesWuCode Fixed. Could you check it out?

nice, this is fixed.

thank you

**Comment by MilesWuCode** [comment]
New Issues

Base table or view not found

- Crop button

- Rengerate button

**Comment by dmitrybubyakin** [comment]
@MilesWuCode Try 2.0.7 pleaes

**Comment by MilesWuCode** [comment]
> @MilesWuCode Try 2.0.7

woking!!
