### ISSUE TITLE
Conflict with BooleanGroup

### ISSUE THREAD

**Issue by nonovd** [dmitrybubyakin/nova-medialibrary-field#50]
**Description**
When a Medialibrary field is used along with a **BooleanGroup field**, the following error is thrown:

```php
Method Illuminate\Support\Collection::isAssoc does not exist.
/var/www/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php#104
```

on the request `GET nova-vendor/dmitrybubyakin/nova-medialibrary-field/{resource}/{resourceId}/media/{field}`

**To Reproduce**
1. Add a Medialibrary field to your Nova Resource
2. Add a BooleanGroup field to your Nova Resource

```php
            BooleanGroup::make('Accessibility', 'options')
                ->options([
                    'pregnant' => 'Pregnant Women',
                    'prm' => 'Persons with Reduced Mobility',
                    'hearing_impared' => 'Hearing-impared Person',
                    'visually_impared' => 'Visually-impared Person',
                ])
                ->hideFromIndex(),

            Medialibrary::make('Photos', 'pictures', 'public')
                ->hideFromIndex()
            ,
```
3. Go to your Nova Resource index page

**Expected behavior**
Medialibrary field should work the same way it does without BooleanGroup field.

**Environemnt:**
 - Ubuntu 16.04.6 LTS
 - PHP 7.3.13
 - Laravel 5.8.35
 - Nova 2.10.0
 - Spatie Media Library 7.18.0
 - Dmitrybubyakin Nova Media Library Field 2.0.4

**Comment by dmitrybubyakin** [comment]
@nonovd Hi. It looks like `/nova-vendor/*` requests don't register `Laravel\Nova\NovaServiceProvider` which registers the `Collection::isAssoc` macro. You can add these lines in your service provider and the problem will be fixed.

```php
Collection::macro('isAssoc', function () {
    return Arr::isAssoc($this->toBase()->all());
});
```

**Comment by nonovd** [comment]
@dmitrybubyakin Thank you it does work !

If I do understand, this is something that needs to be fixed on the Nova end ?

**Comment by dmitrybubyakin** [comment]
@nonovd I think, yes. I've created an [issue](https://github.com/laravel/nova-issues/issues/2332). If they won't, I'll fix it in this package.

**Comment by dmitrybubyakin** [comment]
@nonovd Hi. Looks like they've fixed this. Could you please check it out? https://github.com/laravel/nova/compare/v2.10.1...v2.11.0#diff-0ec68fe3510a239b312d5d7c16324482R39

**Comment by nonovd** [comment]
I can confirm we no longer need [the fix provided by](https://github.com/dmitrybubyakin/nova-medialibrary-field/issues/50#issuecomment-582899685) @dmitrybubyakin with the [latest release of Nova 2.11.0](https://github.com/laravel/nova/releases/tag/v2.11.0).
