### ISSUE TITLE
не работает кроп

### ISSUE THREAD

**Issue by dmitriytretyakov** [dmitrybubyakin/nova-medialibrary-field#52]
Добрый вечер! Спасибо за отличное решение. Не получается настроить кроп изображений, почему-то после конверсии оно выглядит также как и оригинальное изображение.

В модели добавил:
```
public function registerMediaConversions(Media $media = null)
    {

        $this->addMediaConversion('thumb')
            ->width(212)
            ->height(106);

        $this->addMediaConversion('cropped');
    }
```

В ресурсе добавил:

```
Medialibrary::make('Изображения', 'images', 'medialibrary')->rules('required')->croppable('cropped')->mediaOnIndex(5)->fields(function () {
                return [
                    Text::make('Имя файла', 'name')
                        ->rules('required', 'min:2'),
                    Text::make('Alt атрибут', 'custom_properties->alt'),
                    Text::make('Title атрибут', 'custom_properties->title'),
                ];
            }),
```

Что я делаю не так?

P.S. В Mysql в таблице медиа у изображения в поле manipulations появилось следующее: " {"cropped": {"manualCrop": "482,454,245,-4", "orientation": "auto"}}"

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Привет, очереди работают? Если выполнить regenerate, отработает?

**Comment by dmitrybubyakin** [comment]
Попробуй добавить `$this->addMediaConversion('cropped')->nonQueued()`, так работает?

**Comment by dmitriytretyakov** [comment]
Неа, не помог ни `php artisan medialibrary:regenerate` ни nonQueued() и повторная попытка кропа.

**Comment by dmitriytretyakov** [comment]
Не знаю чем тебе помочь, может у тебя он ищет изображения из collection_name = default? У меня collection_name = images

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/storing-media-specific-manipulations/#main

```php
$mediaItems = $newsItem->getMedia('images');
$mediaItems[0]->manipulations = [
   'thumb' => ['orientation' => '90'],
];

// This will cause the thumb conversions to be regenerated.
$mediaItems[0]->save();
```

Так работает?

**Comment by dmitriytretyakov** [comment]
Нет, запустил этот код, на всякий случай сделал regenerate, но ничего не изменилось у thumb

**Comment by dmitriytretyakov** [comment]
При этом в mysql манипуляция сохранилась.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov значит проблема в чем-то другом. Если бы код выше работал, значит проблема была бы в medialibrary-field.

**Comment by filipzlamala** [comment]
I had the same issue. The problem was in the `registerMediaConversions`, you need to add your media collection with `performOnCollections` method:
`$this->addMediaConversion('cropped')->performOnCollections('images')`
