### ISSUE TITLE
Persist media on submit

### ISSUE THREAD

**Issue by mpanius** [dmitrybubyakin/nova-medialibrary-field#53]
If you just choose media, and don't hit 'upload' button, it results in empty field after model creation. Should be great to automaticaly upload images (or, at least, throw warning).

Если добавить изображения (choose files), а потом не нажать "загрузить" (upload), то после сохранения поле пустое. Хорошо бы сделать опцию с автоматической загрузкой, ну или на худой конец предупреждать, что изображения не загружены.

**Comment by dmitrybubyakin** [comment]
@mpanius Привет. Как вариант - загружать (если не загружено) при нажатии save?

**Comment by mpanius** [comment]
Ммм, понятно что это можно сделать ручками, если не решите поправить, то так конечно и сделаю. 

Но немного нелогично интерфейсно так, как оно сейчас из коробки. Человек  загружал, потом нажал вроде сохранить, и у него все пропало.

**Comment by mpanius** [comment]
Отдельно хотел бы поблагодарить за такой логичный и уже сейчас хорошо работающий компонент, после ebess/nova-media-library прям бальзам на душу

**Comment by dmitrybubyakin** [comment]
@mpanius Проверь 2.0.8 https://github.com/dmitrybubyakin/nova-medialibrary-field/commit/18c6081a4ca37a36fff0e2c614a5e15bb3bbc563#diff-a41cdc0e92ce32ca227caf81ee5dee2cR231

**Comment by mpanius** [comment]
На выходных проверю, спасибо
P.S. Я там письмо написал на адрес в профиле, с ящика с corp.ixbt.com, посмотри плз

**Comment by mpanius** [comment]
Все работает корректно, как с 1, так и с несколькими medialibrary
