### ISSUE TITLE
Autouploading fails silently when rules are not met.

### ISSUE THREAD

**Issue by bernhardh** [dmitrybubyakin/nova-medialibrary-field#56]
If i active autoupload and try to upload an image with a wrong size, I get no error message. The form is just stuck. In Chrome Console I get the error `422 (Unprocessable Entity) ` with 

```
{message: "The given data was invalid.", errors: {file: ["file hat ungültige Bildabmessungen."]}}
``` 
Translate to "file has wrong dimmensions".

**Comment by dmitrybubyakin** [comment]
@bernhardh Hi. Could you provide more details?

**Comment by bernhardh** [comment]
Sorry, of course. Was already working on more details.

I have the following field:

```php
Medialibrary::make("Teaser", "teaser")
    ->single()
    ->attachRules('image', 'dimensions:min_width=780')
    ->autouploading()
```

Now when I try to upload an images with minimum width of 780 (for example https://i.picsum.photos/id/849/800/300.jpg) it works as expected.

![image](https://user-images.githubusercontent.com/642292/77158270-477fe900-6aa3-11ea-8881-36678b61e91e.png)

Trying it with a smaller one, for example this one https://i.picsum.photos/id/849/200/300.jpg 

![image](https://user-images.githubusercontent.com/642292/77158319-60889a00-6aa3-11ea-8550-ccb2bc948c75.png)

But I dont get a message, that or why it fails. There should the alert bubble with "file hat ungültige Bildabmessungen." from the failed post request.

Btw. also without `->autouploading()` it doesn't work. I then see this

![image](https://user-images.githubusercontent.com/642292/77158470-ae9d9d80-6aa3-11ea-9008-9fb5f029a7bf.png)

And after clicking on "Upload" nothing happens.

**Comment by dmitrybubyakin** [comment]
@bernhardh Validation errors are displayed when you are hovering the file ![validation errors](https://raw.githubusercontent.com/dmitrybubyakin/nova-medialibrary-field/master/docs/create.png)

**Comment by bernhardh** [comment]
Thanks for your feedback and your great package. 

Ah, ok I didn't thought about hovering over the image/icon for a message and I think its not the expected nova behaviour. A was letting some colleagues try it by their own, without telling them to hover and everybody was expecting an error notifcation and only one out of five colleagues found the info by hovering.

Not sure if its a lot of work, but is it possible to add and the "error bubble"?

**Comment by dmitrybubyakin** [comment]
@bernhardh Yes, I'll do that. Thank you:)

**Comment by bernhardh** [comment]
Or alternativly show the error message directly under the image. This is the default behaviour for most of the other errors on other fields in nova, like "required", etc.

**Comment by dmitrybubyakin** [comment]
@bernhardh Hi. Could you please check it out?

**Comment by bernhardh** [comment]
Perfect! Thats exactly what I would expect! Thank you so much.
