### ISSUE TITLE
Call to undefined method App\Models\User::registerMediaCollections()

### ISSUE THREAD

**Issue by tanaticreative** [dmitrybubyakin/nova-medialibrary-field#58]
using base implemention             Medialibrary::make('Media')->single(),

**Comment by dmitrybubyakin** [comment]
@tanaticreative What traits are used in your `App\Models\User`?

**Comment by tanaticreative** [comment]
@dmitrybubyakin 
`    use Notifiable;
    use LogsActivity;
    use HasRoles;
    use SoftDeletes;`
What should be?

**Comment by dmitrybubyakin** [comment]
@tanaticreative This package uses https://github.com/spatie/laravel-medialibrary, so your model should implement the `Spatie\MediaLibrary\HasMedia\HasMedia` interface.

**Comment by tanaticreative** [comment]
@dmitrybubyakin А где в readme об этом написано?

**Comment by dmitrybubyakin** [comment]
@tanaticreative Написано о чем? Что spatie/laravel-medialibrary используется?

**Comment by tanaticreative** [comment]
о том что требуется добавить  этот трейт к модели

**Comment by dmitrybubyakin** [comment]
@tanaticreative Это написано в документации к spatie/laravel-medialibrary
