### ISSUE TITLE
Support for php 7.2

### ISSUE THREAD

**Issue by JoshMoreno** [dmitrybubyakin/nova-medialibrary-field#59]
I ran php codesniffer and the only error that's showing up is `Trailing comma's are not allowed in function calls in PHP 7.2 or earlier` for these files:

- /src/Fields/Medialibrary.php line 269
- /src/Fields/Support/MediaCollectionRules.php line 24
- /src/Http/Controllers/AttachController.php line 69
- /src/Http/Controllers/CropController.php line 21
- /src/Resources/Media.php line 32
- /tests/Integration/AttachControllerTest.php line 213

If you're open to a pull request I can fix the above and downgrade the minimum php version in the composer.json.

Let me know

**Comment by dmitrybubyakin** [comment]
@JoshMoreno Hi. I'm not going to downgrade the minimum php version. You can fork this repository and do that.
