### ISSUE TITLE
The upload button isn't enabled

### ISSUE THREAD

**Issue by austinkregel** [dmitrybubyakin/nova-medialibrary-field#6]
Hia! I just installed this package on my installation of nova, and when I tried to upload a photo the upload button isn't enabled.

<img width="602" alt="screen shot 2018-12-30 at 4 35 08 pm" src="https://user-images.githubusercontent.com/5355937/50551583-183c4c80-0c51-11e9-8eab-c364622f6ceb.png">

It seems like it just needs to recompiled or something, but I'm not totally sure. I also don't see any errors in the JS console.

**Comment by dmitrybubyakin** [comment]
@austinkregel What is your browser?

**Comment by austinkregel** [comment]
I use Google Chrome

**Comment by austinkregel** [comment]
I just checked on safari and it doesn't work there either.

**Comment by austinkregel** [comment]
From the look of it all the package seems to be missing the `vue-progress-button` package, and some stiles on the button.

**Comment by dmitrybubyakin** [comment]
@austinkregel `progress-button` is a nova component which is globally registered

**Comment by austinkregel** [comment]
Oh okay 🤔 
@dmitrybubyakin which version of Nova are you developing with? I could have an older version

**Comment by dmitrybubyakin** [comment]
@austinkregel I am developing with the latest version of Nova

**Comment by austinkregel** [comment]
🤔 Interesting, that seems to be the issue. I wonder which version added the `progress-button`, if you happen to find out can you add that information to your readme 😄

**Comment by dmitrybubyakin** [comment]
@austinkregel The `progress-button` component has been added in v1.2.0. I think, you can define your own `progress-button` component and this is going to work.

**Comment by austinkregel** [comment]
I ultimately upgrade to the latest version of Nova to make sure that it's all going to work 😄thanks for helping me figure out this silly issue 😂
