### ISSUE TITLE
Ошибки при запуске примеров

### ISSUE THREAD

**Issue by tanaticreative** [dmitrybubyakin/nova-medialibrary-field#60]
Такое ощущение не один из приведенных примеров в реадми не работает.
Base table or view not found: 1146 Table 'relo.media' 
Method DmitryBubyakin\NovaMedialibraryField\Fields\Medialibrary::title does not exist.
Method DmitryBubyakin\NovaMedialibraryField\Fields\Medialibrary::attachRules does not exist
Method DmitryBubyakin\NovaMedialibraryField\Fields\Medialibrary::single does not exist. 
Как понимаю по причине того что в документации описан последняя версия модуля . А он рассчитан на php 7.3. Для 7.2 грузится v 1.2 . И функционал не работает
Не понятно почему про это ни слова в readme ?

**Comment by dmitrybubyakin** [comment]
@tanaticreative Привет, спасибо за уточнение, добавлю в readme ссылку на v1.
