### ISSUE TITLE
После кропа не обновляется preview

### ISSUE THREAD

**Issue by dmitriytretyakov** [dmitrybubyakin/nova-medialibrary-field#62]
Сделал у поля ->previewUsing('cropped'), сам кроп работает, но после кропа в preview загружается тоже самое изображение что и было, возможно потому что пусть полностью совпадает с предыдущим. Помогает только перезагрузка страницы

**Comment by dmitriytretyakov** [comment]
Понятно, что если используется отложенная генерация в отдельной очереди, то вопрос сложный, но с nonQueued() тоже не дружит

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov поправлю, спасибо

**Comment by dmitriytretyakov** [comment]
Как вариант можно просто к ссылке на изображение добавить параметр с рандомным значением, чтобы браузер грузил изображение всегда заново. Например ?t=123132

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov в 2.0.14 поправил

**Comment by dmitriytretyakov** [comment]
А Flexible в 2.0.14 поддерживается?

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov нет, он в другой ветке https://github.com/dmitrybubyakin/nova-medialibrary-field/pull/69, но там все актуальные изменения.
