### ISSUE TITLE
Creating has error

### ISSUE THREAD

**Issue by MilesWuCode** [dmitrybubyakin/nova-medialibrary-field#64]
Return value of DmitryBubyakin\NovaMedialibraryField\Http\Requests\MedialibraryRequest::fieldUuid() must be of the type string,

- php 7.4.4
- medialibrary 8.0
- nova 3.2.2

**Comment by dmitrybubyakin** [comment]
@MilesWuCode Hi. Could you share your field configuration?

**Comment by MilesWuCode** [comment]
```php
use DmitryBubyakin\NovaMedialibraryField\Fields\Medialibrary;
// ...
Medialibrary::make('cover'),
```
limit 3 hours
http://61f9377e.ngrok.io/resources/books
email: test@email.com
password:test

**Comment by dmitrybubyakin** [comment]
@MilesWuCode What request fails?

**Comment by MilesWuCode** [comment]
i dnot know , just open create page , popup error
![截圖 2020-04-10 下午2 44 46](https://user-images.githubusercontent.com/1192835/78969649-0a56c600-7b3a-11ea-9e7f-d560fbbf6416.png)
![截圖 2020-04-10 下午2 45 06](https://user-images.githubusercontent.com/1192835/78969657-0e82e380-7b3a-11ea-9174-7ece8384b6ed.png)

**Comment by dmitrybubyakin** [comment]
@MilesWuCode Do you use any other packages? Seems like the value for the cover attribute is overwritten.

**Comment by dmitrybubyakin** [comment]
@MilesWuCode Got same error after updating Nova. I'm looking into it.

**Comment by MilesWuCode** [comment]
thank you !! 

> @MilesWuCode Got same error after updating Nova. I'm looking into it.

**Comment by dmitrybubyakin** [comment]
@MilesWuCode Fixed. Check out v3.0.1 please.
