### ISSUE TITLE
Cannot update Media informations

### ISSUE THREAD

**Issue by nonovd** [dmitrybubyakin/nova-medialibrary-field#65]
## Problem

Update Request is not sent because of a Javascript error when trying to update a media from the Edit Modal.

![image](https://user-images.githubusercontent.com/12936673/78998504-139b5f00-7b49-11ea-8b2b-ca1c286f751a.png)

## To reproduce

1. On any media item, click Edit Icon to open the Edit Modal.
2. Click "Update Medium" to send the form.

## Env

Laravel Nova 3.3.2
Medialibrary-field 3.0.1

**Comment by dmitrybubyakin** [comment]
@nonovd Thank you for the PR. Checkout v3.0.2 please.
