### ISSUE TITLE
Previewing using temp url 

### ISSUE THREAD

**Issue by mostafakram** [dmitrybubyakin/nova-medialibrary-field#71]
Hi, 

I am need to preview images on nova (details and index) with temp urls from s3 

I have used the downloadUsing 
```php
downloadUsing(function (Media $media){
    return $media->getTemporaryUrl(now()->addMinutes(5));
})
```

And it works as expected 

But the previewUsing doesn't 

```php
previewUsing(function (Media $media) {
    return $media->getTemporaryUrl(now()->addMinutes(5));
})
```

![Screen Shot 2020-04-26 at 12 30 58 PM](https://user-images.githubusercontent.com/25792357/80304932-cb6f7400-87b9-11ea-8735-b11c16f314e4.png)

One more thing, the download url from the view is not the temp one as well. 

Thanks

**Comment by mostafakram** [comment]
I have found that in MediaPresenter.php the difference between `downloadUrl` and `previewUrl` is calling `appendTimestamp` on the `previewUrl` which i believe breaks the tempURL 

if its changed from 
`'previewUrl' => $this->appendTimestamp($this->previewUrl()),`
to 
`'previewUrl' => $this->previewUrl(),` 

It works as expected

**Comment by dmitrybubyakin** [comment]
@mostafakram Hi. Thank you for pointing this out! I'll fix that as I can.

**Comment by mostafakram** [comment]
Thank you for your promptness 

Please note that i am on version 2.0.14 of the package 

And i have a suggestion to fix this without backward compatibility

add new variable public `$attachTimeStamp;` to  the filed 

add new method 
```php
public function attachTimeStamp(bool $attachTimeStamp = true): self
    {
        $this->attachTimeStamp = $attachTimeStamp;

        return $this;
    }
```

call this method in constructor 
```php
public function __construct(string $name, string $collectionName = 'default', string $diskName = '') 
{
    // ...
    $this->attachTimeStamp();
}
```

and in MediaPresenter 

change previewUrl to in `toArray()`
```
'previewUrl' => $this->field->attachTimeStamp ? $this->appendTimestamp($this->previewUrl()) : $this->previewUrl(),
``` 

Now calling the field this way to make it work 
```php
->previewUsing(function (Media $media) {
    return $media->getTemporaryUrl(now()->addMinutes(5));
})
->attachTimeStamp(false)
```
What do you think ? Would you like me to submit PR with this solution ?

**Comment by dmitrybubyakin** [comment]
@mostafakram Hi. Could you please checkout 2.0.16? Now it appends only when cropping enabled and can be disabled with `Medialibrary::appendTimestampToPreview(false)` (must be called after `Madialibrary::croppable()`). See 998603f. Can I close the issue?

**Comment by mostafakram** [comment]
Awesome 💪 

Thank you @dmitrybubyakin 

Yes its fixed and you can close the issue 

Just two points please

- Please update the readme with the changes for others using the package 
- As i mentioned above the download url in the window from the view button is not the temp one, how can update it? 
![Screen Shot 2020-04-27 at 11 38 51 AM](https://user-images.githubusercontent.com/25792357/80357758-b824dd00-887b-11ea-8523-86a3c8497d48.png)

**Comment by dmitrybubyakin** [comment]
@mostafakram You can override default media fields https://github.com/dmitrybubyakin/nova-medialibrary-field#fields

**Comment by mostafakram** [comment]
Great, thanks
