### ISSUE TITLE
Thanks for this awesome package, that will be great if it has translation support

### ISSUE THREAD

**Issue by winter-ice** [dmitrybubyakin/nova-medialibrary-field#72]

**Comment by dmitrybubyakin** [comment]
@winter-ice Hi. It has translation support - https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/resources/js/components/Medialibrary/MediaUploading.vue#L25

**Comment by winter-ice** [comment]
1. By default, the fields doesn't use translation helper. We have to custom fields to do this - https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/3b94a6de1736459078257b5f9d7e4229b8a03b1b/src/Fields/Support/MediaFields.php#L19

2. I view the source code. And I didn't found how to translate the panel title 😞 .

3. It will be better if the package has own translation file. It will be helpful for contribute multi-language support. And We don't need edit it in Nova's translation file either.

**Comment by dmitrybubyakin** [comment]
> 1. By default, the fields doesn't use translation helper. We have to custom fields to do this -
Will be fixed.

> 2\. I view the source code. And I didn't found how to translate the panel title 😞 .
Which panel?

> 3\. It will be better if the package has own translation file. It will be helpful for contribute multi-language support. And We don't need edit it in Nova's translation file either.

I'll try to do that.

If you have any thoughts how to make this package better, please let me know, I'll be happy to help.

**Comment by winter-ice** [comment]
I had do the 1 and 3 through my own way.
Could you please tell me how to translate the panel title? 
![image](https://user-images.githubusercontent.com/24680921/80348773-e1a42f80-88a0-11ea-87e1-797173e3ab75.png)
In detail and form page

**Comment by dmitrybubyakin** [comment]
@winter-ice Could you please checkout a new version? I've added the translation file.

**Comment by winter-ice** [comment]
Before I create this issue, I just installed this package

**Comment by winter-ice** [comment]
Sorry, I just notice that you released new v2 version, but I installed v3 version just now

**Comment by dmitrybubyakin** [comment]
@winter-ice https://github.com/dmitrybubyakin/nova-medialibrary-field/commit/0ce1ddaae858abca388a1848ecc7e08712ad0114

**Comment by winter-ice** [comment]
could you please release the new v3 version? I will update it use composer

**Comment by dmitrybubyakin** [comment]
@winter-ice Yes, I did the same for v3.

**Comment by winter-ice** [comment]
I had updated to new version. Seems it works well, I haven't use all feature of this package. I will make a PR for Chinese Localization after I test all feature related to localization.

**Comment by winter-ice** [comment]
Where is the `:resource` defined? Seems it always be `medium`?

**Comment by dmitrybubyakin** [comment]
@winter-ice It uses https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/src/Resources/Media.php#L10. I'll add a few translations.

**Comment by dmitrybubyakin** [comment]
@winter-ice https://github.com/dmitrybubyakin/nova-medialibrary-field/commit/615da532e33a84fa80e57f334c771e63c100158c
