### ISSUE TITLE
how to prevent preview from being squished on smaller screens

### ISSUE THREAD

**Issue by vesper8** [dmitrybubyakin/nova-medialibrary-field#78]
Hi there, am really enjoying your package, thank you for making it.

I'm having an issue where if I want to display 5 image previews on the index page, it looks good on wide screen but on smaller screen the rounded images get squished together.

This may be a result of using gregoriohc/laravel-nova-theme-responsive

Still, I would like to know if you have any idea how I can prevent the images from being squished? By possibly setting a min-width on the column field or by using withMeta to make sure the images don't use percentage-based units

Here's a screenshot of the squishing that is happening

![Screen Shot 2020-05-13 at 6 34 32 PM](https://user-images.githubusercontent.com/816028/81833921-fba06c00-9548-11ea-9ecf-266760300c86.png)

Thank you

**Comment by dmitrybubyakin** [comment]
@vesper8 Hi. I'll add possibility to set `min-width` via `withMeta`.

**Comment by vesper8** [comment]
thank you! that should hopefully do the trick. Will you add it on the whole column or on a per-media-item basis? I think it would need to be on a per-item otherwise the column may be larger than it needs to be as now every row has at least 5 media items

**Comment by dmitrybubyakin** [comment]
@vesper8 Can be fixed like this:

**Comment by vesper8** [comment]
@dmitrybubyakin I think you meant to paste a solution and forgot to paste it? I'd love to see it. Thanks!

**Comment by dmitrybubyakin** [comment]
@vesper8 It is a typo. This bug is fixed now. https://github.com/dmitrybubyakin/nova-medialibrary-field/commit/da50f2f4cba240682b3b22f7ca48d2e92ee53584#diff-e70003cf2af24434c6254620001f382eea022a99f57448551d76378719bdcad8R37

If you want customize it - try `Medialibrary::withMeta(['indexPreviewClassList' => 'classes that you need'])`
