### ISSUE TITLE
Не работает required в сочетании с epartment/nova-dependency-container

### ISSUE THREAD

**Issue by dmitriytretyakov** [dmitrybubyakin/nova-medialibrary-field#79]
Не работает required (возможно и rules в целом) в сочетании с epartment/nova-dependency-container

Пример:

```
NovaDependencyContainer::make([
                Medialibrary::make('Большой десктоп', 'xl_image', 'medialibrary')->rules(['required'])->previewUsing('thumb')->single()->attachExisting()->fields(function () {
                    return [
                        Text::make('Имя файла', 'name')
                            ->rules('required', 'min:2'),
                        Text::make('Alt атрибут', 'custom_properties->alt'),
                        Text::make('Title атрибут', 'custom_properties->title'),
                    ];
                }),
                Medialibrary::make('Маленький десктоп', 'lg_image', 'medialibrary')->rules(['required'])->previewUsing('thumb')->single()->attachExisting()->fields(function () {
                    return [
                        Text::make('Имя файла', 'name')
                            ->rules('required', 'min:2'),
                        Text::make('Alt атрибут', 'custom_properties->alt'),
                        Text::make('Title атрибут', 'custom_properties->title'),
                    ];
                }),
                Medialibrary::make('Планшет', 'md_image', 'medialibrary')->rules(['required'])->previewUsing('thumb')->single()->attachExisting()->fields(function () {
                    return [
                        Text::make('Имя файла', 'name')
                            ->rules('required', 'min:2'),
                        Text::make('Alt атрибут', 'custom_properties->alt'),
                        Text::make('Title атрибут', 'custom_properties->title'),
                    ];
                }),
                Medialibrary::make('Телефон', 'sm_image', 'medialibrary')->rules(['required'])->previewUsing('thumb')->single()->attachExisting()->fields(function () {
                    return [
                        Text::make('Имя файла', 'name')
                            ->rules('required', 'min:2'),
                        Text::make('Alt атрибут', 'custom_properties->alt'),
                        Text::make('Title атрибут', 'custom_properties->title'),
                    ];
                }),
            ])->dependsOn('type', 'image'),
```

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Проверил, все работает. Валидация не работает в том случае, если dependencies are not satisfied для NovaDependencyContainer.

**Comment by dmitriytretyakov** [comment]
А какие версии пакетов ты используешь?

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov `composer require dev-feat/nova-flexible-content-support`

**Comment by dmitriytretyakov** [comment]
Я имел в виду какая версия новы и NovaDependencyContainer

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov последние версии

**Comment by dmitriytretyakov** [comment]
Проверил. Присмотрись к своему примеру, у тебя на скрине ругается на правило min, а required игнорирует. В моем же примере используется single() изображение и min не подойдет.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov привет, ок, завтра проверю

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov проверил, все работает. 
![image](https://user-images.githubusercontent.com/11477505/83320687-701a2100-a252-11ea-9aeb-545f77957f8c.png)

**Comment by dmitriytretyakov** [comment]
Можешь скинуть пример кода?

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov 
```php
<?php

NovaDependencyContainer::make([
    Medialibrary::make('Dependency', 'dependency')
        ->rules('required', 'array')
        ->attachExisting()
])->dependsOnNotEmpty('content'),
```

**Comment by dmitriytretyakov** [comment]
А проверял для single()?

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov да

```php
<?php

// collection registration
class Post extends Model implements HasMedia
{
    use HasMediaTrait;

    public function registerMediaCollections()
    {
        $this->addMediaCollection('dependency')->singleFile();
    }
}

// fields
return [
    Text::make('Content'),
    
    NovaDependencyContainer::make([
        Medialibrary::make('Dependency', 'dependency')
            ->rules('required')
            ->attachExisting()
            ->single()
    ])->dependsOnNotEmpty('content')
];
```

**Comment by dmitriytretyakov** [comment]
Не знаю что сказать, у меня поле 
```
Medialibrary::make('Большой десктоп', 'xl_image', 'medialibrary')->rules(['required'])->previewUsing('thumb')->single()->attachExisting()->fields(function () {
                    return [
                        Text::make('Имя файла', 'name')
                            ->rules('required', 'min:2'),
                        Text::make('Alt атрибут', 'custom_properties->alt'),
                        Text::make('Title атрибут', 'custom_properties->title'),
                    ];
                }),
```

Если я выношу его из NovaDependencyContainer::make , то начинает работать required, если возвращаю то снова пропускает не возвращая ошибок.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov У тебя условие `dependsOn` выполняется? Если нет, то required не будет работать.

**Comment by dmitriytretyakov** [comment]
Выполняется

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov если medialibrary заменить на любое другое поле, будет работать?

**Comment by dmitriytretyakov** [comment]
Хороший вопрос, завтра гляну

**Comment by dmitriytretyakov** [comment]
Проверил на примере ` Text::make('Ссылка для перехода', 'url')->hideFromIndex()->rules(['required', 'url']),`. Работает как нужно, в любом случае требует заполнить поле.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov `в любом случае требует заполнить поле` - т.е. если условие dependsOn не выполняется, все равно поле required?

**Comment by dmitriytretyakov** [comment]
Не, наверное я неверно выразился. Если условие не выполняется, то rules не срабатывают.

"В любом случае" - тут имело ввиду что и внутри контейнера зависимости и вне его логика работает одинаково.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov если условие dependsOn не выполняется, то текстовое поле (которое required) не обязательно, правильно?

**Comment by dmitriytretyakov** [comment]
Привет, смотри что нашел. Посмотрел сейчас какие данные отправляются при добавлении, а там:
```
большой_десктоп: 4608b290-1f17-4fe0-ae03-8aaccfb81707
маленький_десктоп: 861ee790-7814-45d1-a196-7a2e16594266
планшет: 9e3ef9c3-8b06-4246-94e5-d06794f19cf1
телефон: af499364-b1ec-4a09-b012-e91593f6c81d
```

То есть почему то используются публичные названия вместо названий атрибутов, хотя у всех остальных полей используют атрибуты.

Еще почему-то не сохраняется изображение если его загрузить при создании записи, при редактировании сохраняется успешно.

В твоем примере используется ` Medialibrary::make('Dependency', 'dependency')`, попробуй заменить на  Medialibrary::make('Зависимость', 'dependency') и посмотри что будет.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Привет. Первый аргумент - название (и как атрибут используется), второй аргумент - название коллекции. Если нужно указать кастомный атрибут - https://github.com/dmitrybubyakin/nova-medialibrary-field#attribute

**Comment by dmitriytretyakov** [comment]
Похоже дело не в этом, указание атрибута не помогло.

Не знаю почему, но если использовать изображения в сочетании с NovaDependencyContainer , то не работает валидация и как выяснилось не происходит загрузка изображения при создании записи. Если убираю NovaDependencyContainer, то всё работает как надо.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Пока что нет времени, постараюсь на выходных разобраться в чем проблема.

**Comment by dmitriytretyakov** [comment]
@dmitrybubyakin У тебя работает required_if? Я вытащил поле из контейнера зависимостей, required заработал, а вот required_if не работает почему-то.

**Comment by dmitriytretyakov** [comment]
Интересно. если пишу rules('required_if:type,image'), то не работает. А
```
->rules(function ($request) {
                if ($request->input('type') === 'image') {
                    return ['required'];
                }
                return [];
            })
```
работает

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Работает required_if.
