### ISSUE TITLE
Можно ли сделать обратную сортировку в attachExisting() ?

### ISSUE THREAD

**Issue by dmitriytretyakov** [dmitrybubyakin/nova-medialibrary-field#80]
По ощущениям изображения в нем сортируются по дате добавления и самые старые на первой странице. Можно ли сделать обратную сортировку? Например пользователю нужно четыре раза загрузить одно и тоже изображение. Он грузит его один раз, а дальше трижды выбирает в этом блоке.

P.S. Наверно стоит поправить количество изображений на странице, сейчас их 25 штук, по 8 на каждую строку, в итоге три строки заполнены полностью и одно изображение торчит снизу. Предлагаю сделать либо 24 либо 32.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov попробуй через `attachExistingUsing` https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/v2/tests/Fixtures/Nova/TestPost.php#L30

**Comment by dmitriytretyakov** [comment]
Спасибо, попробую

**Comment by dmitriytretyakov** [comment]
А что скажешь про изменение количество элементов на странице?

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov такой возможности нет, пока что не вижу смысла в ней

**Comment by dmitriytretyakov** [comment]
Смысл в том, что на 25 выглядит некрасиво, нужно либо 24 либо 32
