### ISSUE TITLE
Можно ли вывести информацию об оригинальном  изображении?

### ISSUE THREAD

**Issue by dmitriytretyakov** [dmitrybubyakin/nova-medialibrary-field#81]
Допустим пользователь выбрал или загрузил изображение на контроле. В админке у поля есть текст (рекомендуем использовать размер не мене 500х500), может ли пользователь посмотреть какие ширина и высота у загруженного изображения?

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov `tooltip` - https://github.com/dmitrybubyakin/nova-medialibrary-field#tooltip

**Comment by dmitriytretyakov** [comment]
Спасибо, попробую
