### ISSUE TITLE
Некорректно работает обрезание изображений

### ISSUE THREAD

**Issue by dmitriytretyakov** [dmitrybubyakin/nova-medialibrary-field#89]
Попробовал загрузить вертикальное изображение 1000х1262 пикселя и после этого обрезать изображение. В появившемся окне отображается только центральная часть изображения, а верх и низ не дает включить в область кропа.

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov Можно скрин?

**Comment by dmitriytretyakov** [comment]
![image](https://user-images.githubusercontent.com/34216562/94124482-bd537b80-fe5d-11ea-9200-3e5caf0ff635.png)

**Comment by dmitriytretyakov** [comment]
Там выше голова должна быть, но её никак не выделить

**Comment by dmitrybubyakin** [comment]
@dmitriytretyakov а zoom?
