### ISSUE TITLE
Request: disable fields

### ISSUE THREAD

**Issue by NormanHuth** [dmitrybubyakin/nova-medialibrary-field#90]
How can I disable the fields including the edit popup?

**Comment by dmitrybubyakin** [comment]
@NormanHuth Do you mean hiding all action buttons?

**Comment by NormanHuth** [comment]
I want to remove the edit image function for some images.

![image](https://user-images.githubusercontent.com/26193232/94057552-111f7f80-fde0-11ea-8109-b3f225e06d3e.png)

**Comment by dmitrybubyakin** [comment]
@NormanHuth Try using policies. https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/src/Fields/Support/MediaPresenter.php#L79
