### ISSUE TITLE
Question: croppable for more conversions or withouth

### ISSUE THREAD

**Issue by NormanHuth** [dmitrybubyakin/nova-medialibrary-field#91]
Is it possible to crop the image in general and save it without conversion? Or how to apply this function to multiple conversions (e.g.: conversion['720p', '1080px'])?

**Comment by dmitrybubyakin** [comment]
@NormanHuth I think you should ask this question [here](https://github.com/spatie/laravel-medialibrary/issues). This package relays on spatie/laravel-medialibrary.
