### ISSUE TITLE
Posibility to add an extra copy code button to the field

### ISSUE THREAD

**Issue by bernhardh** [dmitrybubyakin/nova-medialibrary-field#92]
Currently you have the option to copy the url of the media:

![image](https://user-images.githubusercontent.com/642292/94027567-449be300-fdbb-11ea-9277-408c1d00955a.png)

I want to have the posibility to add an additional button to this menu, where I can copy my own (dynamic) value based on the image (generated by a callback). Lets call it `extraCopyCode`. For example, if you want to copy the ID of the media:

```php
Medialibrary::make($label, $collectionName)
    ->extraCopyCode(function($item) {
        return (string)$item->id;
    })
```
then you will get as a copy result: `4711`

Or if you want to be able to copy the image html tag including an predefined css class:

```php
Medialibrary::make($label, $collectionName)
    ->extraCopyCode(function($item) {
        return (string)$item->img()->attributes(['class' => 'my-class']);
    })
```

then you will get as a copy result: `<img class="my-class" src="http://2020.gutekueche.at.local/storage/media/4711/image.jpg" alt="alt name">`

**Comment by dmitrybubyakin** [comment]
@bernhardh Nice feature. I'll implement this ASAP.

**Comment by dmitrybubyakin** [comment]
@bernhardh Please checkout a new version.

**Comment by bernhardh** [comment]
Thanks and great work. It woul be nice, if we can choose if (one of) the button is always visible (outside the dropdown, right next to the delete icon), because this would reduce one extra click, but i like the implementation anyway. Thank you!
