### ISSUE TITLE
Upload media synchronously, respecting the preview order

### ISSUE THREAD

**Issue by tmartty** [dmitrybubyakin/nova-medialibrary-field#94]
So right now when you click on "Upload" the request to upload all media fires synchronously in the same order the images are previewed before uploading. But then depending on how long each request takes, media entries are created in a different order than the original one.

**Is there a way to either make each attach request wait for the previous one to fire, or to preserve the original preview order when uploading?**

**Comment by tmartty** [comment]
Ended up making my own custom field based on `nova-medialibrary-field` and then changing the **upload** method in [MediaUploading.vue](https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/4588d953e61388ba02055efbb76f92113419080f/resources/js/components/Medialibrary/MediaUploading.vue#L154) to the following:

```
async upload() {
    const { attribute, value } = this.context.field
    const { resourceName, resourceId } = this.context

    for (const media of this.mediaToUpload) {
        this.uploading = true
        const formData = new FormData()

        media.fillFormData(formData)

        formData.append('fieldUuid', value)

        const options = {
            onUploadProgress: event => media.handleUploadProgress(event),
        }

        try {
            await Nova.request().post(
                `/nova-vendor/Mountainlab/nova-medialibrary-field/${resourceName}/${resourceId}/media/${attribute}`,
                formData,
                options
            )
            this.handleUploadSucceeded(media)
        } catch (error) {
            this.handleUploadFailed(media, error)
        }
    }
},
```

What I had to do was to basically turn the `forEach` loop into a regular `for` loop, make the whole method async and add a try/catch with await when doing the post to nova.

With this now media is uploaded one by one, allowing you to keep the same order the files had whilst you were previewing them (also same order you selected them from your file system) which can be useful if you had previously ordered files in your local folder.

**Comment by dmitrybubyakin** [comment]
@tmartty Nice solution. Should I add it to the package?

**Comment by tmartty** [comment]
@dmitrybubyakin yes! That would be awesome.

Maybe an `asyncUpload(true/false)` method?

Then something like this should work? Haven't tested it though.

```
if (asyncUpload) {
        try {
            await Nova.request().post(
                `/nova-vendor/Mountainlab/nova-medialibrary-field/${resourceName}/${resourceId}/media/${attribute}`,
                formData,
                options
            )
            this.handleUploadSucceeded(media)
        } catch (error) {
            this.handleUploadFailed(media, error)
        }
} else {
    Nova.request().post(
        `/nova-vendor/Mountainlab/nova-medialibrary-field/${resourceName}/${resourceId}/media/${attribute}
        formData,
        options
    ).then( (error) => {
        this.handleUploadSucceeded(media)
    }).catch( () => {
        this.handleUploadFailed(media, error)
    }
}
```

**Comment by dmitrybubyakin** [comment]
@tmartty I'll try to implement this on the weekends

**Comment by tmartty** [comment]
@dmitrybubyakin did you manage to implement this?
