### ISSUE TITLE
Upload of new file is not working on create/edit view

### ISSUE THREAD

**Issue by mira-thakkar** [dmitrybubyakin/nova-medialibrary-field#96]
I recently try to integrate the package to support spatie/media-library integration in my nova dashboard
Nova Version: 3.12
Laravel Version: 7.28 

it is showing old media uploads in view(index/detail) and form(update). But upload or choose from existing media doesn't work.  

In `Player` resource, to have image  i have added it like this:

```
Medialibrary::make('Image', 'player_image', 's3' , 'player_image')->single()
```

Player Model
```
class Player extends Model implements HasMedia
{
    use InteractsWithMedia, SortableTrait, SerializeDate;

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')
            ->width(config('fanbox.media_size.player.width'))
            ->height(config('fanbox.media_size.player.height'));
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('player_image')
            ->singleFile();
    }

}
```
Can anyone help me with what am i missing here?

**Comment by dmitrybubyakin** [comment]
@mira-thakkar Could you provide more details?

**Comment by mira-thakkar** [comment]
So basically, it is not giving any error on create/update Player resource, but there is no media(player image) added to the database.

**Comment by dmitrybubyakin** [comment]
@mira-thakkar Try this:

```php
Medialibrary::make('Image', 'player_image', 's3')
    ->single()
    -> attachExisting()
```
