### ISSUE TITLE
withResponsiveImages() not working smoothly

### ISSUE THREAD

**Issue by JonathanDoelan** [dmitrybubyakin/nova-medialibrary-field#98]
Thanks for your great work!

I have problems using `->withResponsiveImages()` inside my models `registerMediaConversions` OR `registerMediaCollections` method. When I select a lot of images, I can’t submit the Create(!)-form on my nova-resource. This is because the server waits for a response but generating all those responsive versions of multiple images can take some time. I'm getting errors like "Internal server error", max-execution-time, …

The problem is that after submitting the create-form, all image versions are copied and REgenerated, even if they are already generated!

A solution would be
- **just updating** the fields "model_type" (DmitryBubyakin\NovaMedialibraryField\TransientModel) and "model_id" in the media-table
- OR **just renaming** the folder which contains the (already generated conversions)

It works perfect on the UPDATE-form.

Is there a quick solution for this problem?

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan Hi. Just updating model_name won't work. Check [this](https://spatie.be/docs/laravel-medialibrary/v8/advanced-usage/moving-media) and [this](https://github.com/dmitrybubyakin/nova-medialibrary-field/blob/master/src/Fields/Medialibrary.php#L388) out. 

It looks like you don't use queues for media processing. Queues can perfectly handle this issue.

Another way - you can override `Medialibrary::fillAttribute`.

**Comment by JonathanDoelan** [comment]
@dmitrybubyakin Thx for your recommendations. They led me to the following solution:

```
class Medialibrary extends \DmitryBubyakin\NovaMedialibraryField\Fields\Medialibrary
{
    protected function fillAttribute(NovaRequest $request, $requestAttribute, $model, $attribute): callable
    {
        $callback = null;

        if (is_callable($this->fillCallback)) {
            $callback = call_user_func(
                $this->fillCallback,
                $request,
                $model,
                $attribute,
                $requestAttribute
            );
        }

        if (is_a($model, \Whitecube\NovaFlexibleContent\Layouts\Layout::class)) {
            $model = \Whitecube\NovaFlexibleContent\Flexible::getOriginModel();
        }

        return function () use ($request, $attribute, $model, $callback): void {
            if (is_callable($callback)) {
                $callback();
            }

            if (empty($uuid = $request->input($attribute))) {
                return;
            }

            $propertyName = TransientModel::getCustomPropertyName();

            foreach (TransientModel::make()->getMedia($uuid) as $media) {
				$this->moveToModel($model, $media, $propertyName);
            }
        };
    }

    protected function moveToModel($model, $media, $propertyName)
    {
		$media
			->forgetCustomProperty($propertyName)
			->update([
				'manipulations' => $media->manipulations,
				'model_type' => $model->getMorphClass(),
				'model_id' => $model->id,
				'collection_name' => $this->collectionName,
			]);
    }
}
```

… and it WORKS GREAT!
My problem is, that in my production environment I can’t run queued jobs. :(
So maybe, for this case, you’ll find a way to integrate this kind of customization in your app.

As you can see I’ve extracted the part where the model is moved into a new method. This is what it would look like with your implementation:

```
	protected function moveToModel($model, $media, $propertyName)
	{
        $media
            ->forgetCustomProperty($propertyName)
            ->move($model, $this->collectionName, $this->diskName)
            ->update(['manipulations' => $media->manipulations]);
	}
```

So you could extract it this way, because then it would be safer to extend the Medialibrary class.

**Comment by dmitrybubyakin** [comment]
@JonathanDoelan `Medialibrary::moveMediaToTargetModelUsing`.

**Comment by JonathanDoelan** [comment]
@dmitrybubyakin Thanks a lot!
